'use strict';
    var REPO_OWNER='darzmackz',REPO_NAME='darzmackz.github.io',REPO_BRANCH='main',POSTS_DIR='_posts',PORTFOLIO_FILE='_data/portfolio.json',CONFIG_FILE='_config.yml',ROBOTS_FILE='robots.txt',ADS_FILE='ads.txt',MEDIA_DIR='assets/images';
    var PAGE_FILES={home:'index.html',about:'about.md',contact:'contact.md',privacy:'privacy.md',disclosure:'disclosure.md',editorial:'editorial-policy.md',terms:'terms.md'};
    var TIMEZONE_OFFSET='+0800',SESSION_TTL_MS=7*24*3600*1000,KEY_HASH='admin_pwd_hash',KEY_TOKEN='admin_github_token',KEY_SESSION='admin_session',KEY_SESSION_EXP='admin_session_exp',KEY_POST_AUTOSAVE='post_editor_autosave_v2',KEY_POSTS_PAGE='admin_posts_page',POSTS_PER_PAGE=5;
    var sections=['dashboard','posts','post-editor','portfolio','portfolio-editor','pages','page-editor','media','settings'],postsCache=[],currentPostsPage=1,postsHydratedAll=false,portfolioCache=[],portfolioSha=null,pfTech=[],currentPf=null,currentPost=null,currentPage=null,siteCache={configRaw:'',configSha:null,robotsRaw:'',robotsSha:null,adsRaw:'',adsSha:null},suspendPostAutosave=false,lastAutoPostFile='';
    var templates={lyrics:{title:'Song Title Lyrics and Karaoke Guide',categories:'music, lyrics, karaoke',tags:'lyrics, karaoke, music',excerpt:'A clear and useful introduction to the song, lyrics, and karaoke angle.',content:'## Song Overview\n\nIntroduce the track and why it matters.\n\n## Lyrics and Karaoke Notes\n\n- standout lyric themes\n- sing-along moments\n- audience appeal\n\n## Final Thoughts\n\nWrap up with a short takeaway.\n'},music:{title:'Artist or Track Feature',categories:'music, feature',tags:'music, artist-feature',excerpt:'A short feature highlighting the track, performance, or artist perspective.',content:'## What Makes This Stand Out\n\nDescribe the performance, release, or audience appeal.\n\n## Why It Connects With Listeners\n\nShare what works well and why.\n\n## Final Thoughts\n\nClose with a short takeaway.\n'},tech:{title:'Practical Tech Walkthrough',categories:'tutorial, tech',tags:'tech, tutorial',excerpt:'A practical technical walkthrough with clear steps and a useful outcome.',content:'## Problem\n\nDescribe the issue or goal.\n\n## Solution\n\nExplain the approach and key steps.\n\n## Notes\n\n- best practices\n- caveats\n- follow-up ideas\n'},'youtube-pair':{title:'Artist - Song Title',categories:'music, youtube, lyrics, karaoke',tags:'music, youtube, lyrics, karaoke',excerpt:'A combined post for matching lyrics and karaoke uploads with one cleaner overview.',content:'## What This Post Covers\n\nIntroduce the track or performance and explain why grouping the related uploads is useful.\n\n## Available Video Versions\n\n- Watch the lyrics version here: [Add link](https://www.youtube.com/)\n- Sing along with the karaoke version here: [Add link](https://www.youtube.com/)\n\n## Why It Matters\n\nExplain what makes the performance, arrangement, or sing-along version worth visiting.\n\n## Notes for Readers\n\n- Mention whether more versions may be added later.\n- Link to related pages if helpful.\n'},news:{title:'Technology News Topic',categories:'news, tech',tags:'news, tech, analysis',excerpt:'A draft that turns a news update into a clearer, higher-value article.',content:'## What Happened\n\nSummarize the announcement or event in plain language.\n\n## Why It Matters\n\nExplain who is affected and why this is worth a reader\'s attention.\n\n## Practical Takeaways\n\n- key takeaway\n- caveat or limitation\n- next step for readers\n\n## Source Context\n\n- Source: [Add source link](https://example.com)\n- Angle: explain the original framing of the post\n\n## Before Publishing\n\nAdd a more original explanation before you publish.\n'}};
    function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
    function escJs(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
    function store(k,v){try{localStorage.setItem(k,v)}catch(e){}}
    function load(k){try{return localStorage.getItem(k)}catch(e){return null}}
    function remove(k){try{localStorage.removeItem(k)}catch(e){}}
    function loadPositiveInt(k,fallback){var value=Number(load(k));return Number.isFinite(value)&&value>0?Math.floor(value):(fallback||1)}
    function showAlert(id,t,m){var e=document.getElementById(id);if(!e)return;e.innerHTML='<div class="alert alert-'+t+'">'+m+'</div>';setTimeout(function(){if(e)e.innerHTML=''},6000)}
    async function sha256(msg){var b=new TextEncoder().encode(msg),h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(function(x){return x.toString(16).padStart(2,'0')}).join('')}
    function randomToken(){var a=new Uint8Array(32);crypto.getRandomValues(a);return Array.from(a).map(function(b){return b.toString(16).padStart(2,'0')}).join('')}
    function createSession(){var t=randomToken();store(KEY_SESSION,t);store(KEY_SESSION_EXP,String(Date.now()+SESSION_TTL_MS));return t}
    function isAuthenticated(){var s=load(KEY_SESSION),e=load(KEY_SESSION_EXP),h=load(KEY_HASH);if(!s||!e||!h)return false;if(Date.now()>Number(e)){remove(KEY_SESSION);remove(KEY_SESSION_EXP);return false}return true}
    function today(){var d=new Date();return[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
    function slugify(t){return String(t||'').toLowerCase().replace(/[^\w\s-]/g,'').replace(/[\s_]+/g,'-').replace(/-+/g,'-').replace(/^-+|-+$/g,'')}
    function decode64(b){var bytes=Uint8Array.from(atob(b.replace(/\n/g,'')),function(c){return c.charCodeAt(0)});return new TextDecoder().decode(bytes)}
    function encode64(c){var bytes=new TextEncoder().encode(c),bin='';for(var i=0;i<bytes.length;i++)bin+=String.fromCharCode(bytes[i]);return btoa(bin)}
    function parseFM(raw){var m=raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);if(!m)return{meta:{},content:raw};var meta={};m[1].split(/\r?\n/).forEach(function(line){if(!line.trim())return;var i=line.indexOf(':');if(i===-1)return;var k=line.slice(0,i).trim(),v=line.slice(i+1).trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);if(v==='true')v=true;else if(v==='false')v=false;else if(v.startsWith('[')&&v.endsWith(']'))v=v.slice(1,-1).split(',').map(function(s){return s.trim().replace(/^['"]|['"]$/g,'')}).filter(Boolean);meta[k]=v});return{meta:meta,content:m[2].replace(/^\n+/,'')}}
    function fmVal(v){if(v===true||v===false)return String(v);if(Array.isArray(v))return'['+v.join(', ')+']';return'"'+String(v).replace(/"/g,'\\"')+'"'}
    function buildFM(meta,layout){var l=['---','layout: '+(layout||meta.layout||'post')];Object.keys(meta).forEach(function(k){if(k==='layout')return;var v=meta[k];if(v===''||v===null||typeof v==='undefined')return;l.push(k+': '+fmVal(v))});l.push('---');return l.join('\n')}
    async function ghRequest(method,path,body){var token=load(KEY_TOKEN);if(!token)throw new Error('No GitHub token. Go to Settings and add your token.');var res=await fetch('https://api.github.com/repos/'+REPO_OWNER+'/'+REPO_NAME+'/contents/'+path,{method:method,headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github.v3+json','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!res.ok){var err=await res.json().catch(function(){return{message:res.statusText}});throw new Error(err.message||('GitHub API error: '+res.status))}return res.status===204?null:res.json()}
    async function ghGetFile(path){var f=await ghRequest('GET',path);return{raw:decode64(f.content),sha:f.sha,path:path}}
    async function ghPutFile(path,content,sha,message){var body={message:message,content:encode64(content),branch:REPO_BRANCH};if(sha)body.sha=sha;return ghRequest('PUT',path,body)}
    async function ghPut64(path,b64,sha,message){var body={message:message,content:b64,branch:REPO_BRANCH};if(sha)body.sha=sha;return ghRequest('PUT',path,body)}
    async function ghDelete(path,sha,message){return ghRequest('DELETE',path,{message:message,sha:sha,branch:REPO_BRANCH})}
    async function ghList(path){var r=await ghRequest('GET',path);return Array.isArray(r)?r:[]}
    async function initAuth(){var box=document.getElementById('auth-content');if(!load(KEY_HASH)){box.innerHTML='<div class="alert alert-info"><strong>First-time setup</strong><br>Set a password and add your GitHub token.</div><div id="setup-alert"></div><div class="fg"><label>Admin Password</label><input type="password" id="setup-pwd"></div><div class="fg"><label>Confirm Password</label><input type="password" id="setup-confirm"></div><div class="fg"><label>GitHub Personal Access Token</label><input type="password" id="setup-token" placeholder="ghp_..."></div><button class="btn p full" type="button" data-action="do-setup">Set Up Admin Panel</button>'}else{box.innerHTML='<div id="login-alert"></div><div class="fg"><label>Password</label><input type="password" id="login-pwd" data-enter-action="do-login"></div><button class="btn p full" type="button" data-action="do-login">Login</button>'}}
    async function doSetup(){var p=document.getElementById('setup-pwd').value,c=document.getElementById('setup-confirm').value,t=document.getElementById('setup-token').value.trim();if(!p)return showAlert('setup-alert','error','Password is required.');if(p!==c)return showAlert('setup-alert','error','Passwords do not match.');if(!t)return showAlert('setup-alert','error','GitHub token is required.');store(KEY_HASH,await sha256(p));store(KEY_TOKEN,t);createSession();enterAdmin()}
    async function doLogin(){var p=document.getElementById('login-pwd').value;if(!p)return showAlert('login-alert','error','Enter your password.');if(await sha256(p)!==load(KEY_HASH))return showAlert('login-alert','error','Incorrect password.');createSession();enterAdmin()}
    function isDesktopNav(){return window.matchMedia('(min-width: 768px)').matches}
    function navEls(){return{toggle:document.getElementById('admin-nav-toggle'),nav:document.getElementById('admin-nav')}}
    function setNavMenuOpen(isOpen){var els=navEls(),open=isDesktopNav()?true:!!isOpen;if(!els.nav||!els.toggle)return;els.nav.classList.toggle('is-open',open);els.toggle.setAttribute('aria-expanded',String(open&&!isDesktopNav()))}
    function closeNavMenu(){setNavMenuOpen(false)}
    function syncNavMenu(){setNavMenuOpen(isDesktopNav())}
    function logout(){closeNavMenu();remove(KEY_SESSION);remove(KEY_SESSION_EXP);document.getElementById('admin-view').classList.add('hidden');document.getElementById('auth-view').classList.remove('hidden');initAuth()}
    function setNav(name){['dashboard','posts','portfolio','pages','media','settings'].forEach(function(id){var el=document.getElementById('nav-'+id),active=id===name;if(!el)return;el.classList.toggle('p',active);el.classList.toggle('g',!active);el.setAttribute('aria-pressed',String(active))})}
    function enterAdmin(){document.getElementById('auth-view').classList.add('hidden');document.getElementById('admin-view').classList.remove('hidden');syncNavMenu();showSection(load('admin_last_section')||'dashboard')}
    function showSection(name){sections.forEach(function(s){var el=document.getElementById('sec-'+s);if(el)el.classList.add('hidden')});var cur=document.getElementById('sec-'+name);if(cur)cur.classList.remove('hidden');store('admin_last_section',name);if(['dashboard','posts','portfolio','pages','media','settings'].indexOf(name)!==-1)setNav(name);closeNavMenu();if(name==='dashboard')refreshDashboard();if(name==='posts')loadPosts();if(name==='portfolio')loadPortfolio();if(name==='media')loadMedia();if(name==='settings')prefillSettings()}
    function postStatus(meta){var d=String(meta.date||today()).slice(0,10);if(meta.status==='draft'||meta.published===false)return'draft';if(meta.status==='scheduled'||d>today())return'scheduled';return'published'}
    function statusPill(s){return'<span class="pill '+s+'">'+esc(s.charAt(0).toUpperCase()+s.slice(1))+'</span>'}
    function postUrl(name){var c=String(name).replace('.md',''),dp=c.slice(0,10).split('-'),slug=c.slice(11);return'/'+dp.join('/')+'/'+slug+'/'}
    async function ensurePostHydrated(post){if(post&&post.meta&&typeof post.content!=='undefined'&&post.status)return post;var full=await ghGetFile(post.path),p=parseFM(full.raw);post.raw=full.raw;post.sha=full.sha;post.meta=p.meta;post.content=p.content;post.status=postStatus(p.meta);return post}
    async function ensurePostsHydrated(items){if(!items||!items.length)return items;for(var i=0;i<items.length;i++)await ensurePostHydrated(items[i]);return items}
    function setPostsPage(page){currentPostsPage=Math.max(1,Number(page)||1);store(KEY_POSTS_PAGE,String(currentPostsPage))}
    async function loadPosts(){var wrap=document.getElementById('posts-wrap');wrap.innerHTML='<div class="loading"><span class="spin"></span> Loading posts...</div>';try{var files=await ghList(POSTS_DIR);postsCache=files.filter(function(f){return f.name.endsWith('.md')}).sort(function(a,b){return String(b.name||'').localeCompare(String(a.name||''))});currentPostsPage=loadPositiveInt(KEY_POSTS_PAGE,currentPostsPage);postsHydratedAll=false;await renderPostsList()}catch(err){wrap.innerHTML='<div class="alert alert-error">'+esc(err.message)+'</div>'}}
    function uiIcon(name){return'<svg class="ui-icon" aria-hidden="true"><use href="#icon-'+name+'"></use></svg>'}
    function postsPager(total,page){var pages=Math.max(1,Math.ceil(total/POSTS_PER_PAGE)),buttons='',start=Math.max(1,page-2),end=Math.min(pages,start+4);if(end-start<4)start=Math.max(1,end-4);for(var i=start;i<=end;i++)buttons+='<button class="btn sm g'+(i===page?' pager-current':'')+'" type="button" data-action="posts-page" data-page="'+i+'"'+(i===page?' aria-current="page"':'')+'>'+i+'</button>';return'<div class="posts-toolbar"><p class="muted">Showing '+(total?(((page-1)*POSTS_PER_PAGE)+1):0)+'-'+Math.min(total,page*POSTS_PER_PAGE)+' of '+total+' posts</p><div class="posts-pagination"><button class="btn sm g" type="button" data-action="posts-page" data-page="'+Math.max(1,page-1)+'"'+(page===1?' disabled':'')+'>Prev</button>'+buttons+'<button class="btn sm g" type="button" data-action="posts-page" data-page="'+Math.min(pages,page+1)+'"'+(page===pages?' disabled':'')+'>Next</button></div></div>'}
    async function renderPostsList(){var wrap=document.getElementById('posts-wrap'),q=(document.getElementById('post-search').value||'').toLowerCase(),f=document.getElementById('post-filter').value,items=postsCache.slice();if(q||f!=='all'){if(!postsHydratedAll){wrap.innerHTML='<div class="loading"><span class="spin"></span> Filtering posts...</div>';await ensurePostsHydrated(postsCache);postsHydratedAll=true}items=postsCache.filter(function(p){var hay=((p.meta.title||'')+' '+p.name).toLowerCase();return(!q||hay.indexOf(q)!==-1)&&(f==='all'||p.status===f)})}var totalPages=Math.max(1,Math.ceil(items.length/POSTS_PER_PAGE));if(currentPostsPage>totalPages)setPostsPage(totalPages);else setPostsPage(currentPostsPage);var pageItems=items.slice((currentPostsPage-1)*POSTS_PER_PAGE,currentPostsPage*POSTS_PER_PAGE);await ensurePostsHydrated(pageItems);if(!items.length){wrap.innerHTML='<div class="card"><p class="muted">No posts match the current filters.</p></div>';return}wrap.innerHTML=postsPager(items.length,currentPostsPage)+'<div class="posts">'+pageItems.map(function(p){return'<div class="post"><div class="info"><div class="title">'+esc(p.meta.title||p.name)+' '+statusPill(p.status)+'</div><div class="meta">'+esc(String(p.meta.date||'').slice(0,10))+' | '+esc(p.name)+' | <a href="'+esc(postUrl(p.name))+'" target="_blank" rel="noopener">View</a></div></div><div class="actions"><button class="btn sm has-icon" type="button" data-action="edit-post" data-path="'+esc(p.path)+'">'+uiIcon('edit')+'<span>Edit</span></button><button class="btn d sm has-icon" type="button" data-action="remove-post" data-path="'+esc(p.path)+'">'+uiIcon('trash')+'<span>Delete</span></button></div></div>'}).join('')+'</div>'+postsPager(items.length,currentPostsPage)}
    function changePostsPage(page){setPostsPage(page);renderPostsList()}
    function onPostFiltersChanged(){setPostsPage(1);renderPostsList()}
    function autoPostFile(title,date){return(date||today())+'-'+slugify(title||'post')+'.md'}
    function postValues(){return{title:document.getElementById('pe-title').value.trim(),date:document.getElementById('pe-date').value||today(),categories:document.getElementById('pe-cats').value.trim(),tags:document.getElementById('pe-tags').value.trim(),youtube:document.getElementById('pe-youtube').value.trim(),desc:document.getElementById('pe-desc').value.trim(),seoTitle:document.getElementById('pe-seo-title').value.trim(),social:document.getElementById('pe-social').value.trim(),canonical:document.getElementById('pe-canonical').value.trim(),file:document.getElementById('pe-file').value.trim(),content:document.getElementById('pe-content').value,status:document.getElementById('pe-status').value}}
    function setPostTemplateMode(isNew){var card=document.getElementById('post-template-card'),actions=document.getElementById('post-template-actions');if(card)card.classList.remove('hidden');if(actions)actions.classList.toggle('hidden',!isNew)}
    function setPostValues(v){v=v||{title:'',date:today(),categories:'',tags:'',youtube:'',desc:'',seoTitle:'',social:'',canonical:'',file:'',content:'',status:'draft'};suspendPostAutosave=true;document.getElementById('pe-title').value=v.title||'';document.getElementById('pe-date').value=v.date||today();document.getElementById('pe-cats').value=v.categories||'';document.getElementById('pe-tags').value=v.tags||'';document.getElementById('pe-youtube').value=v.youtube||'';document.getElementById('pe-desc').value=v.desc||'';document.getElementById('pe-seo-title').value=v.seoTitle||'';document.getElementById('pe-social').value=v.social||'';document.getElementById('pe-canonical').value=v.canonical||'';document.getElementById('pe-file').value=v.file||'';document.getElementById('pe-content').value=v.content||'';document.getElementById('pe-status').value=v.status||'draft';lastAutoPostFile=v.file||autoPostFile(v.title,v.date);suspendPostAutosave=false;syncPostEditor()}
    function openPostEditor(){currentPost=null;remove(KEY_POST_AUTOSAVE);document.getElementById('post-editor-title').textContent='New Post';showSection('post-editor');setPostTemplateMode(true);setPostValues()}
    async function editPost(path){try{var f=await ghGetFile(path),p=parseFM(f.raw);currentPost={path:path,sha:f.sha,file:path.split('/').pop()};remove(KEY_POST_AUTOSAVE);document.getElementById('post-editor-title').textContent='Edit Post';showSection('post-editor');setPostTemplateMode(false);setPostValues({title:p.meta.title||'',date:String(p.meta.date||today()).slice(0,10),categories:Array.isArray(p.meta.categories)?p.meta.categories.join(', '):String(p.meta.categories||'').replace(/[\[\]]/g,''),tags:Array.isArray(p.meta.tags)?p.meta.tags.join(', '):String(p.meta.tags||'').replace(/[\[\]]/g,''),youtube:p.meta.youtube_id||'',desc:p.meta.description||'',seoTitle:p.meta.seo_title||'',social:p.meta.social_image||'',canonical:p.meta.canonical_url||'',file:currentPost.file,content:p.content,status:postStatus(p.meta)})}catch(err){showAlert('posts-wrap','error',esc(err.message))}}
    function applyTemplate(name){var v=postValues(),titleAuto=autoPostFile(v.title,v.date);if(name==='blank'){document.getElementById('pe-title').value='';document.getElementById('pe-cats').value='';document.getElementById('pe-tags').value='';document.getElementById('pe-youtube').value='';document.getElementById('pe-desc').value='';document.getElementById('pe-seo-title').value='';document.getElementById('pe-social').value='';document.getElementById('pe-canonical').value='';document.getElementById('pe-content').value='';if(!v.file||v.file===titleAuto||v.file===lastAutoPostFile)document.getElementById('pe-file').value='';syncPostEditor();return}var t=templates[name];if(!t)return;document.getElementById('pe-title').value=t.title;document.getElementById('pe-cats').value=t.categories;document.getElementById('pe-tags').value=t.tags;document.getElementById('pe-desc').value=t.excerpt;document.getElementById('pe-content').value=t.content;document.getElementById('pe-youtube').value='';document.getElementById('pe-seo-title').value='';document.getElementById('pe-social').value='';document.getElementById('pe-canonical').value='';if(!v.file||v.file===titleAuto||v.file===lastAutoPostFile)document.getElementById('pe-file').value='';syncPostEditor()}
    function onPostStatus(){if(document.getElementById('pe-status').value==='scheduled'&&document.getElementById('pe-date').value<=today()){var d=new Date();d.setDate(d.getDate()+2);document.getElementById('pe-date').value=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}syncPostEditor()}
    function syncPostEditor(){var v=postValues(),autoFile=autoPostFile(v.title,v.date),fileField=document.getElementById('pe-file');if(!fileField.value.trim()||fileField.value.trim()===lastAutoPostFile)fileField.value=autoFile;lastAutoPostFile=fileField.value.trim()||autoFile;document.getElementById('pe-slug').textContent=postUrl(lastAutoPostFile);if(!suspendPostAutosave&&!currentPost)store(KEY_POST_AUTOSAVE,JSON.stringify(postValues()));refreshPostPreview();updatePostChecklist()}
    async function ensurePreviewData(includePosts){if(!siteCache.configRaw){try{var cfg=await ghGetFile(CONFIG_FILE);siteCache.configRaw=cfg.raw;siteCache.configSha=cfg.sha}catch(e){}}if(includePosts&&!postsCache.length){try{await loadPosts()}catch(e){}}if(includePosts&&postsCache.length&&!postsHydratedAll){try{await ensurePostsHydrated(postsCache);postsHydratedAll=true}catch(e){}}}
    function configMap(){var raw=siteCache.configRaw||'',keys=['title','description','author','author_fullname','email','lang','timezone','url','baseurl','logo','profile_image','github_username','twitter_username','facebook_url','youtube_channel'];return keys.reduce(function(map,key){map[key]=yamlVal(raw,key)||'';return map},{})}
    function stripHtmlText(text){return String(text||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
    function truncateWords(text,count){var words=String(text||'').trim().split(/\s+/).filter(Boolean);return words.length>count?words.slice(0,count).join(' ')+'...':words.join(' ')}
    function formatPreviewDate(value,mode){var d=new Date(value);if(isNaN(d.getTime()))return String(value||'');if(mode==='xml'){return d.toISOString()}var months=['January','February','March','April','May','June','July','August','September','October','November','December'];return months[d.getMonth()]+' '+d.getDate()+', '+d.getFullYear()}
    function excerptForPost(post){return post.meta.description||truncateWords(stripHtmlText(post.content||''),30)}
    function postWordCount(text){return String(text||'').trim().split(/\s+/).filter(Boolean).length}
    function headingCount(text){var m=String(text||'').match(/^##?\s+/gm);return m?m.length:0}
    function normalizedTitleKey(text){return slugify(String(text||'').replace(/\b(lyrics|karaoke|official|video)\b/gi,' ').replace(/\s+/g,' ').trim())}
    function resolvePath(path){var cfg=configMap(),base=cfg.baseurl||'';return (base&&base!=='/'?base:'')+path}
    function resolveValue(expr,context){expr=expr.trim();if((expr.startsWith("'")&&expr.endsWith("'"))||(expr.startsWith('"')&&expr.endsWith('"')))return expr.slice(1,-1);if(expr==='site.posts.size')return String(postsCache.length);if(expr==='tag')return context.tag||'';var parts=expr.split('.'),root=parts.shift();var source=root==='site'?configMap():root==='page'?(context.page||{}):root==='post'?(context.post||{}):root==='tag'?context.tag||'':{};var value=source;for(var i=0;i<parts.length;i++){if(value==null)break;value=value[parts[i]]}return value==null?'':value}
    function applyFilters(value,filters){var out=value;for(var i=0;i<filters.length;i++){var filter=filters[i].trim();if(filter==='relative_url')out=resolvePath(String(out||''));else if(filter==='absolute_url'){var cfg=configMap();out=(cfg.url||'')+resolvePath(String(out||''))}else if(filter==='strip_html')out=stripHtmlText(out);else if(filter.indexOf('truncatewords:')===0)out=truncateWords(out,parseInt(filter.split(':')[1],10)||30);else if(filter==='date_to_xmlschema')out=formatPreviewDate(out,'xml');else if(filter.indexOf('date:')===0)out=formatPreviewDate(out,'text')}return out}
    function renderLiquidVars(text,context){return String(text||'').replace(/{{\s*([^}]+)\s*}}/g,function(_,expr){var parts=expr.split('|');var value=resolveValue(parts.shift(),context);return applyFilters(value,parts)})}
    function previewPostContext(post){return{title:post.meta.title||post.name,url:postUrl(post.name),date:post.meta.date||'',youtube_id:post.meta.youtube_id||'',excerpt:excerptForPost(post),tags:Array.isArray(post.meta.tags)?post.meta.tags:[]}}
    function renderLatestPostsSection(){if(!postsCache.length)return'';var items=postsCache.slice(0,3).map(function(post){var ctx=previewPostContext(post),tags=ctx.tags.map(function(tag){return'<span class="tag">#'+esc(tag)+'</span>'}).join('');return'<li class="post-list-item"><h2><a href="'+esc(resolvePath(ctx.url))+'">'+esc(ctx.title)+'</a></h2><div class="post-meta"><time datetime="'+esc(formatPreviewDate(ctx.date,'xml'))+'">'+esc(formatPreviewDate(ctx.date,'text'))+'</time>'+(ctx.youtube_id?'<span class="youtube-badge">&#9654; Video</span>':'')+tags+'</div>'+(ctx.excerpt?'<p class="post-excerpt">'+esc(ctx.excerpt)+'</p>':'')+'<a class="read-more" href="'+esc(resolvePath(ctx.url))+'">Read more &rarr;</a></li>'}).join('');return'<section class="section-panel"><div class="section-intro"><h2 class="section-title">Latest Posts</h2><p class="section-copy">Recent updates from the blog, including music features and creator-focused content.</p></div><ul class="post-list">'+items+'</ul><p class="mt-lg"><a class="btn btn-primary" href="'+esc(resolvePath('/blog/'))+'">Browse all posts</a></p></section>'}
    function renderHomeLoops(text){
      text=text.replace(/{%\s*if site\.posts\.size > 0\s*%}[\s\S]*?<a class="btn btn-primary" href="{{ '\/blog\/' \| relative_url }}">Browse all posts<\/a><\/p>\s*<\/section>\s*{%\s*endif\s*%}/g,function(){return renderLatestPostsSection()});
      return text.replace(/{%\s*if site\.posts\.size > 0\s*%}[\s\S]*?{%\s*endif\s*%}/g,function(){return renderLatestPostsSection()});
    }
    function previewDocument(content,title){var cfg=configMap(),siteTitle=cfg.title||'Preview',lang=cfg.lang||'en',cssHref=(cfg.url||'')+resolvePath('/assets/css/main.css');return'<!DOCTYPE html><html lang="'+esc(lang)+'"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>'+esc(title||siteTitle)+'</title><link rel="stylesheet" href="'+esc(cssHref)+'"><style>body{margin:0;background:#f8fafc}.site-main{padding:32px 0}.preview-note{font:12px/1.4 sans-serif;color:#64748b;padding:12px 16px;border-bottom:1px solid #e2e8f0;background:#fff}.preview-liquid{margin:1rem 0}</style></head><body><div class="preview-note">Live preview using site styles and resolved config values.</div><main class="site-main" id="main"><div class="container">'+content+'</div></main></body></html>'}
    async function renderPreview(targetId,raw,context){await ensurePreviewData(raw.indexOf('site.posts')!==-1);var host=document.getElementById(targetId),template=renderHomeLoops(String(raw||''),context);template=template.replace(/{%[\s\S]*?%}/g,function(match){return'<div class="preview-liquid code">'+esc(match)+'</div>'});template=renderLiquidVars(template,context);var frame=document.createElement('iframe');frame.className='preview-frame';frame.setAttribute('title','Live preview');host.classList.add('preview-frame-host');host.innerHTML='';host.appendChild(frame);frame.srcdoc=previewDocument(md(template),context.page&&context.page.title?context.page.title:configMap().title)}
    async function refreshPostPreview(){await renderPreview('post-preview',document.getElementById('pe-content').value,{page:{title:document.getElementById('pe-title').value.trim(),description:document.getElementById('pe-desc').value.trim()}});if(!suspendPostAutosave&&!currentPost)store(KEY_POST_AUTOSAVE,JSON.stringify(postValues()))}
    function updatePostChecklist(){var host=document.getElementById('post-checks');if(!host)return;var v=postValues(),words=postWordCount(v.content),headings=headingCount(v.content),titleKey=normalizedTitleKey(v.title),duplicate=postsCache.some(function(p){if(currentPost&&p.path===currentPost.path)return false;return normalizedTitleKey(((p.meta&&p.meta.title)||p.name||''))===titleKey&&titleKey!==''}),checks=[{ok:v.title.trim().length>=20,text:'Title is descriptive enough for readers and search results.'},{ok:v.desc.length>=70,text:'Meta description is descriptive (70+ characters).'},{ok:words>=180,text:'Content has at least 180 words.'},{ok:headings>=2,text:'Content uses at least two headings for readability.'},{ok:!!v.categories,text:'Categories are present.'},{ok:!!v.tags,text:'Tags are present.'},{ok:!duplicate,text:'Title does not duplicate an existing post too closely.'},{ok:!v.social||v.social.indexOf('/assets/images/')===0||v.social.indexOf('http')===0,text:'Social image path looks valid.'},{ok:!v.canonical||/^https?:\/\//.test(v.canonical),text:'Canonical URL is absolute when provided.'},{ok:v.status!=='scheduled'||v.date>today(),text:'Scheduled posts use a future date.'}];host.innerHTML=checks.map(function(c){return'<div class="check '+(c.ok?'pass':'warn')+'">'+(c.ok?'&#10003;':'&#9888;')+' '+esc(c.text)+'</div>'}).join('')}
    async function savePost(){var v=postValues();if(!v.title)return showAlert('post-editor-alert','error','Title is required.');var file=v.file||(v.date+'-'+slugify(v.title)+'.md');if(!/\.md$/i.test(file))file+='.md';var path=POSTS_DIR+'/'+file,originalPath=currentPost?currentPost.path:null,isRename=!!(currentPost&&originalPath!==path);if(!currentPost||isRename){try{await ghGetFile(path);return showAlert('post-editor-alert','error','A post with this filename already exists.')}catch(e){}}var meta={title:v.title,date:v.date+' 12:00:00 '+TIMEZONE_OFFSET,categories:v.categories?v.categories.split(',').map(function(s){return s.trim()}).filter(Boolean):[],tags:v.tags?v.tags.split(',').map(function(s){return s.trim()}).filter(Boolean):[],youtube_id:v.youtube||'',description:v.desc||'',seo_title:v.seoTitle||'',social_image:v.social||'',canonical_url:v.canonical||'',status:v.status,published:v.status!=='draft'};var full=buildFM(meta,'post')+'\n\n'+v.content.trim()+'\n',btn=document.getElementById('save-post-btn');btn.disabled=true;btn.innerHTML='<span class="spin"></span> Saving...';try{if(isRename){await ghPutFile(path,full,null,'Rename and update: '+v.title);await ghDelete(originalPath,currentPost.sha,'Remove old post file: '+currentPost.file)}else{await ghPutFile(path,full,currentPost?currentPost.sha:null,currentPost?'Update: '+v.title:'Add: '+v.title)}var r=await ghGetFile(path);currentPost={path:path,sha:r.sha,file:file};document.getElementById('pe-file').value=file;document.getElementById('post-editor-title').textContent='Edit Post';setPostTemplateMode(false);remove(KEY_POST_AUTOSAVE);showAlert('post-editor-alert','success',isRename?'Post renamed and saved. GitHub Pages will rebuild shortly.':'Post saved. GitHub Pages will rebuild shortly.');await loadPosts()}catch(err){showAlert('post-editor-alert','error',esc(err.message))}finally{btn.disabled=false;btn.textContent='Save Post'}}
    async function removePost(path){var p=postsCache.find(function(x){return x.path===path});if(!p||!confirm('Delete "'+(p.meta.title||p.name)+'"?'))return;try{await ghDelete(p.path,p.sha,'Delete: '+p.name);await loadPosts()}catch(err){alert('Error: '+err.message)}}
    async function loadPortfolio(){var wrap=document.getElementById('portfolio-wrap');wrap.innerHTML='<div class="loading"><span class="spin"></span> Loading portfolio...</div>';try{var r=await ghGetFile(PORTFOLIO_FILE);portfolioSha=r.sha;portfolioCache=JSON.parse(r.raw);if(!portfolioCache.length){wrap.innerHTML='<div class="card"><p class="muted">No portfolio items yet.</p></div>';return}wrap.innerHTML='<div class="portfolio">'+portfolioCache.map(function(item,i){var badges=(item.tech||[]).map(function(t){return'<span class="pill">'+esc(t)+'</span>'}).join(' ');return'<div class="pf"><div class="pf-icon" aria-hidden="true">'+esc(item.icon||'')+'</div><div class="info"><div class="title">'+esc(item.title)+'</div><div class="meta">'+(item.subtitle?esc(item.subtitle)+' | ':'')+badges+'</div></div><div class="actions actions-compact"><button class="btn sm has-icon" type="button" data-action="move-portfolio" data-index="'+i+'" data-direction="-1">'+uiIcon('arrow-up')+'<span>Up</span></button><button class="btn sm has-icon" type="button" data-action="move-portfolio" data-index="'+i+'" data-direction="1">'+uiIcon('arrow-down')+'<span>Down</span></button><button class="btn sm has-icon" type="button" data-action="open-portfolio-editor" data-index="'+i+'">'+uiIcon('edit')+'<span>Edit</span></button><button class="btn d sm has-icon" type="button" data-action="remove-portfolio" data-index="'+i+'">'+uiIcon('trash')+'<span>Delete</span></button></div></div>'}).join('')+'</div>'}catch(err){wrap.innerHTML='<div class="alert alert-error">'+esc(err.message)+'</div>'}}
    function openPortfolioEditor(i){currentPf=i;pfTech=[];if(i!==null&&typeof i!=='undefined'){var item=portfolioCache[i];document.getElementById('pf-editor-title').textContent='Edit Portfolio Item';document.getElementById('pf-icon').value=item.icon||'';document.getElementById('pf-title').value=item.title||'';document.getElementById('pf-subtitle').value=item.subtitle||'';document.getElementById('pf-description').value=item.description||'';document.getElementById('pf-link').value=item.link||'';document.getElementById('pf-link-text').value=item.link_text||'';pfTech=Array.isArray(item.tech)?item.tech.slice():[]}else{document.getElementById('pf-editor-title').textContent='New Portfolio Item';['pf-icon','pf-title','pf-subtitle','pf-description','pf-link','pf-link-text'].forEach(function(id){document.getElementById(id).value=''})}renderPfTags();showSection('portfolio-editor')}
    function renderPfTags(){var box=document.getElementById('pf-tags-box'),input=document.getElementById('pf-tags');Array.from(box.querySelectorAll('.chip')).forEach(function(c){c.remove()});pfTech.forEach(function(tag,i){var chip=document.createElement('span');chip.className='chip';chip.innerHTML=esc(tag)+' <button type="button" data-action="remove-pf-tag" data-index="'+i+'" aria-label="Remove '+esc(tag)+' tag">&times;</button>';box.insertBefore(chip,input)})}
    function addPfTag(v){v=v.trim();if(v&&pfTech.indexOf(v)===-1){pfTech.push(v);renderPfTags()}}
    function removePfTag(i){pfTech.splice(i,1);renderPfTags()}
    function pfTagKey(e){var input=document.getElementById('pf-tags');if(e.key==='Enter'||e.key===','){e.preventDefault();addPfTag(input.value.replace(/,/g,''));input.value=''}else if(e.key==='Backspace'&&input.value===''&&pfTech.length){pfTech.pop();renderPfTags()}}
    async function savePortfolioItem(){var title=document.getElementById('pf-title').value.trim();if(!title)return showAlert('pf-editor-alert','error','Title is required.');var part=document.getElementById('pf-tags').value.trim();if(part){addPfTag(part);document.getElementById('pf-tags').value=''}var item={id:slugify(title),icon:document.getElementById('pf-icon').value.trim()||'📌',title:title,subtitle:document.getElementById('pf-subtitle').value.trim(),description:document.getElementById('pf-description').value.trim(),tech:pfTech.slice(),link:document.getElementById('pf-link').value.trim(),link_text:document.getElementById('pf-link-text').value.trim()};if(currentPf===null||typeof currentPf==='undefined')portfolioCache.push(item);else portfolioCache[currentPf]=item;var btn=document.getElementById('save-pf-btn');btn.disabled=true;btn.innerHTML='<span class="spin"></span> Saving...';try{await ghPutFile(PORTFOLIO_FILE,JSON.stringify(portfolioCache,null,2)+'\n',portfolioSha,(currentPf===null||typeof currentPf==='undefined'?'Add portfolio item: ':'Update portfolio item: ')+title);var r=await ghGetFile(PORTFOLIO_FILE);portfolioSha=r.sha;portfolioCache=JSON.parse(r.raw);showAlert('pf-editor-alert','success','Portfolio item saved.')}catch(err){showAlert('pf-editor-alert','error',esc(err.message))}finally{btn.disabled=false;btn.textContent='Save Item'}}
    async function removePf(i){var item=portfolioCache[i];if(!item||!confirm('Delete "'+item.title+'"?'))return;portfolioCache.splice(i,1);try{await ghPutFile(PORTFOLIO_FILE,JSON.stringify(portfolioCache,null,2)+'\n',portfolioSha,'Delete portfolio item: '+item.title);var r=await ghGetFile(PORTFOLIO_FILE);portfolioSha=r.sha;portfolioCache=JSON.parse(r.raw);loadPortfolio()}catch(err){alert('Error: '+err.message)}}
    async function movePf(i,d){var n=i+d;if(n<0||n>=portfolioCache.length)return;var t=portfolioCache[i];portfolioCache[i]=portfolioCache[n];portfolioCache[n]=t;try{await ghPutFile(PORTFOLIO_FILE,JSON.stringify(portfolioCache,null,2)+'\n',portfolioSha,'Reorder portfolio items');var r=await ghGetFile(PORTFOLIO_FILE);portfolioSha=r.sha;portfolioCache=JSON.parse(r.raw);loadPortfolio()}catch(err){alert('Error: '+err.message)}}
    async function openPageEditor(key){currentPage={key:key,path:PAGE_FILES[key],sha:null,meta:{},layout:'page'};document.getElementById('page-editor-title').textContent='Edit '+key.charAt(0).toUpperCase()+key.slice(1)+' Page';showSection('page-editor');try{var f=await ghGetFile(currentPage.path),p=parseFM(f.raw);currentPage.sha=f.sha;currentPage.meta=p.meta;currentPage.layout=p.meta.layout||'page';document.getElementById('pg-title').value=p.meta.title||'';document.getElementById('pg-desc').value=p.meta.description||'';document.getElementById('pg-seo').value=p.meta.seo_title||'';document.getElementById('pg-social').value=p.meta.social_image||'';document.getElementById('pg-canonical').value=p.meta.canonical_url||'';document.getElementById('pg-permalink').value=p.meta.permalink||'';document.getElementById('pg-noindex').checked=p.meta.noindex===true;document.getElementById('pg-content').value=p.content;refreshPagePreview();updatePageChecks()}catch(err){showAlert('page-editor-alert','error',esc(err.message))}}
    function syncPageField(k){if(!currentPage)return;var map={title:'pg-title',description:'pg-desc',seo_title:'pg-seo',social_image:'pg-social',canonical_url:'pg-canonical',permalink:'pg-permalink',noindex:'pg-noindex'},el=document.getElementById(map[k]);currentPage.meta[k]=el.type==='checkbox'?el.checked:el.value.trim();updatePageChecks()}
    async function refreshPagePreview(){await renderPreview('page-preview',document.getElementById('pg-content').value,{page:{title:document.getElementById('pg-title').value.trim(),description:document.getElementById('pg-desc').value.trim(),seo_title:document.getElementById('pg-seo').value.trim(),social_image:document.getElementById('pg-social').value.trim(),canonical_url:document.getElementById('pg-canonical').value.trim(),permalink:document.getElementById('pg-permalink').value.trim()}})}
    function updatePageChecks(){var c=document.getElementById('pg-content').value||'',checks=[{ok:!!document.getElementById('pg-title').value.trim(),text:'Title is set.'},{ok:document.getElementById('pg-desc').value.trim().length>=40,text:'Description is present and descriptive.'},{ok:c.trim().split(/\s+/).filter(Boolean).length>=80,text:'Page content has at least 80 words.'},{ok:!document.getElementById('pg-canonical').value.trim()||/^https?:\/\//.test(document.getElementById('pg-canonical').value.trim()),text:'Canonical URL is absolute when provided.'}];document.getElementById('page-checks').innerHTML=checks.map(function(x){return'<div class="check '+(x.ok?'pass':'warn')+'">'+(x.ok?'&#10003;':'&#9888;')+' '+esc(x.text)+'</div>'}).join('')}
    async function savePage(){if(!currentPage)return;var meta=Object.assign({},currentPage.meta,{title:document.getElementById('pg-title').value.trim(),description:document.getElementById('pg-desc').value.trim(),seo_title:document.getElementById('pg-seo').value.trim(),social_image:document.getElementById('pg-social').value.trim(),canonical_url:document.getElementById('pg-canonical').value.trim(),permalink:document.getElementById('pg-permalink').value.trim(),noindex:document.getElementById('pg-noindex').checked}),full=buildFM(meta,currentPage.layout)+'\n\n'+document.getElementById('pg-content').value.trim()+'\n',btn=document.getElementById('save-page-btn');btn.disabled=true;btn.innerHTML='<span class="spin"></span> Saving...';try{await ghPutFile(currentPage.path,full,currentPage.sha,'Update '+currentPage.path);var r=await ghGetFile(currentPage.path);currentPage.sha=r.sha;showAlert('page-editor-alert','success','Page saved.')}catch(err){showAlert('page-editor-alert','error',esc(err.message))}finally{btn.disabled=false;btn.textContent='Save Page'}}
    function file64(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(e){resolve(e.target.result.split(',')[1])};r.onerror=reject;r.readAsDataURL(file)})}
    async function putBinary(file,path,message){var b64=await file64(file),sha=null;try{sha=(await ghGetFile(path)).sha}catch(e){}return ghPut64(path,b64,sha,message)}
    async function loadMedia(){var wrap=document.getElementById('media-wrap');wrap.innerHTML='<div class="loading"><span class="spin"></span> Loading media...</div>';try{var files=await ghList(MEDIA_DIR);files=files.filter(function(f){return /\.(png|jpe?g|gif|svg|webp|ico)$/i.test(f.name)});if(!files.length){wrap.innerHTML='<div class="card"><p class="muted">No media files found yet.</p></div>';return}wrap.innerHTML=files.map(function(f){var path='/'+MEDIA_DIR+'/'+f.name,markdown='!['+f.name+']('+path+')';return'<div class="mitem"><img src="'+esc(path)+'" alt="'+esc(f.name)+'"><div class="muted media-name">'+esc(f.name)+'</div><div class="stack"><button class="btn sm" type="button" data-action="copy-media-markdown" data-markdown="'+esc(markdown)+'">Copy Markdown</button><button class="btn sm" type="button" data-action="copy-media-path" data-path="'+esc(path)+'">Copy Path</button></div></div>'}).join('')}catch(err){wrap.innerHTML='<div class="alert alert-error">'+esc(err.message)+'</div>'}}
    async function uploadMedia(){var files=document.getElementById('media-upload').files;if(!files||!files.length)return showAlert('media-alert','error','Select one or more images first.');for(var i=0;i<files.length;i++)await putBinary(files[i],MEDIA_DIR+'/'+files[i].name,'Upload media: '+files[i].name);document.getElementById('media-upload').value='';showAlert('media-alert','success','Media upload complete.');loadMedia()}
    async function uploadEditorMedia(){var input=document.getElementById('pe-media'),file=input.files[0];if(!file)return showAlert('post-editor-alert','error','Select an image first.');await putBinary(file,MEDIA_DIR+'/'+file.name,'Upload media: '+file.name);insertAtCursor(document.getElementById('pe-content'),'!['+file.name+'](/'+MEDIA_DIR+'/'+file.name+')');input.value='';refreshPostPreview();updatePostChecklist();showAlert('post-editor-alert','success','Image uploaded and inserted into the post.')}
    function getEd(){return document.getElementById('pe-content')} function getPgEd(){return document.getElementById('pg-content')} function insertAtCursor(ta,text){var s=ta.selectionStart,e=ta.selectionEnd;ta.value=ta.value.slice(0,s)+text+ta.value.slice(e);ta.focus();ta.selectionStart=ta.selectionEnd=s+text.length}
    function insertWrap(b,a,p){var ta=getEd(),sel=ta.value.slice(ta.selectionStart,ta.selectionEnd)||p;insertAtCursor(ta,b+sel+a)} function insertLine(p,ph){insertAtCursor(getEd(),p+(ph||''))} function insertBlock(b,p,a){insertAtCursor(getEd(),b+p+a)} function insertPageWrap(b,a,p){insertAtCursor(getPgEd(),b+p+a);refreshPagePreview()} function insertPageLine(p,ph){insertAtCursor(getPgEd(),p+(ph||''));refreshPagePreview()} function tabKey(e){if(e.key!=='Tab')return;e.preventDefault();insertAtCursor(e.target,'  ')}
    function mdInline(text){var html=esc(text||'');html=html.replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img src="$2" alt="$1" style="max-width:100%;border-radius:8px;">');html=html.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>');html=html.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');html=html.replace(/\*([^*]+)\*/g,'<em>$1</em>');html=html.replace(/`([^`]+)`/g,'<code>$1</code>');return html}
    function liquidPreview(text){return'<div class="code">'+esc(text)+'</div>'}
    function md(markdown){var lines=String(markdown||'').replace(/\r\n/g,'\n').split('\n'),html=[],para=[],list=[],quote=[],code=[],block=[],inCode=false,inHtmlBlock=false,inLiquidBlock=false;function flushParagraph(){if(!para.length)return;html.push('<p>'+mdInline(para.join('<br>'))+'</p>');para=[]}function flushList(){if(!list.length)return;html.push('<ul>'+list.map(function(item){return'<li>'+mdInline(item)+'</li>'}).join('')+'</ul>');list=[]}function flushQuote(){if(!quote.length)return;html.push('<blockquote>'+mdInline(quote.join('<br>'))+'</blockquote>');quote=[]}function flushCode(){if(!code.length)return;html.push('<pre><code>'+esc(code.join('\n'))+'</code></pre>');code=[]}function flushBlock(){if(!block.length)return;var text=block.join('\n');if(inLiquidBlock)html.push(liquidPreview(text));else html.push(text);block=[]}for(var i=0;i<lines.length;i++){var line=lines[i],trimmed=line.trim();if(trimmed.startsWith('```')){flushParagraph();flushList();flushQuote();if(inCode){flushCode();inCode=false}else{inCode=true}continue}if(inCode){code.push(line);continue}if(inHtmlBlock){block.push(line);if(/>$/.test(trimmed)||/^<\/[A-Za-z]/.test(trimmed)||/\/>$/.test(trimmed)) { flushBlock(); inHtmlBlock=false; }continue}if(inLiquidBlock){block.push(line);if(/^({%\s*endif\s*%}|{%\s*endfor\s*%}|{%\s*endunless\s*%}|{%\s*endcase\s*%}|{%\s*endcapture\s*%}|{%\s*endraw\s*%})$/.test(trimmed)){flushBlock();inLiquidBlock=false}continue}if(!trimmed){flushParagraph();flushList();flushQuote();continue}if(/^{[%{]/.test(trimmed)){flushParagraph();flushList();flushQuote();block=[line];if(/^({%\s*if|{%\s*for|{%\s*unless|{%\s*case|{%\s*capture|{%\s*raw)/.test(trimmed)){inLiquidBlock=true}else{html.push(liquidPreview(line));block=[]}continue}if(/^<[^>]*$/.test(trimmed)&&!/>\s*$/.test(trimmed)){flushParagraph();flushList();flushQuote();block=[line];inHtmlBlock=true;continue}if(/^<[^>]+>/.test(trimmed)){flushParagraph();flushList();flushQuote();html.push(line);continue}if(/^### /.test(trimmed)){flushParagraph();flushList();flushQuote();html.push('<h3>'+mdInline(trimmed.slice(4))+'</h3>');continue}if(/^## /.test(trimmed)){flushParagraph();flushList();flushQuote();html.push('<h2>'+mdInline(trimmed.slice(3))+'</h2>');continue}if(/^# /.test(trimmed)){flushParagraph();flushList();flushQuote();html.push('<h1>'+mdInline(trimmed.slice(2))+'</h1>');continue}if(/^- /.test(trimmed)){flushParagraph();flushQuote();list.push(trimmed.slice(2));continue}if(/^> /.test(trimmed)){flushParagraph();flushList();quote.push(trimmed.slice(2));continue}flushList();flushQuote();para.push(trimmed)}flushParagraph();flushList();flushQuote();flushCode();if(block.length)flushBlock();return html.join('')||'<p class="muted">Nothing to preview yet.</p>'}
    async function refreshDashboard(){document.getElementById('dash-stats').innerHTML='<div class="loading"><span class="spin"></span> Loading dashboard...</div>';try{if(!postsCache.length)await loadPosts();if(postsCache.length&&!postsHydratedAll){await ensurePostsHydrated(postsCache);postsHydratedAll=true}var keys=Object.keys(PAGE_FILES),pages=[];for(var i=0;i<keys.length;i++){var key=keys[i],f=await ghGetFile(PAGE_FILES[key]),p=parseFM(f.raw);pages.push({key:key,path:PAGE_FILES[key],meta:p.meta,content:p.content})}var pf=await ghGetFile(PORTFOLIO_FILE);portfolioCache=JSON.parse(pf.raw);renderDashboard(postsCache,pages,portfolioCache)}catch(err){showAlert('dashboard-alert','error',esc(err.message))}}
    function stat(label,val){return'<div class="stat"><div class="k">'+esc(label)+'</div><div class="v">'+esc(val)+'</div></div>'}
    function item(label,val){return'<div class="item"><strong>'+esc(label)+'</strong><div class="muted">'+esc(String(val))+'</div></div>'}
    function links(text){var out=[],m,r=/\[[^\]]+\]\(([^)]+)\)/g,h=/href="([^"]+)"/g;while((m=r.exec(text)))out.push(m[1]);while((m=h.exec(text)))out.push(m[1]);return out}
    function health(posts,pages){var issues=[],seen={};posts.forEach(function(p){var t=String(p.meta.title||'').trim(),key=normalizedTitleKey(t),words=postWordCount(p.content||'');if(!t)issues.push({t:'Missing title',d:p.name});if(!p.meta.description)issues.push({t:'Missing description',d:p.name});if(words<180)issues.push({t:'Thin post draft',d:(p.meta.title||p.name)+' is under 180 words.'});if(!(Array.isArray(p.meta.tags)?p.meta.tags.length:String(p.meta.tags||'').trim()))issues.push({t:'Missing tags',d:p.name});if(t){if(seen[key])issues.push({t:'Duplicate title pattern',d:t});seen[key]=1}});var known=Object.keys(PAGE_FILES).map(function(k){return'/'+PAGE_FILES[k].replace(/\.md$/,'/').replace(/index\.html$/,'')}).concat(posts.map(function(p){return postUrl(p.name)}));posts.concat(pages).forEach(function(x){links(x.content||'').forEach(function(l){if(l.startsWith('/')&&!l.startsWith('/assets/')&&known.every(function(r){return l.indexOf(r)!==0}))issues.push({t:'Possible broken internal link',d:l+' in '+(x.name||x.path||x.key)})})});['privacy','disclosure','editorial','terms','contact','about'].forEach(function(key){if(!pages.some(function(p){return p.key===key}))issues.push({t:'Missing trust page',d:key+' page is not being tracked.'})});var drafts=posts.filter(function(p){return p.status==='draft'});if(drafts.length)issues.push({t:'Draft posts pending review',d:drafts.length+' draft(s) found.'});return issues.slice(0,12)}
    function renderDashboard(posts,pages,pf){var pub=posts.filter(function(p){return p.status==='published'}).length,dr=posts.filter(function(p){return p.status==='draft'}).length,sch=posts.filter(function(p){return p.status==='scheduled'}).length,words=posts.reduce(function(s,p){return s+String(p.content||'').split(/\s+/).filter(Boolean).length},0);document.getElementById('dash-stats').innerHTML=[stat('Published Posts',pub),stat('Drafts',dr),stat('Scheduled',sch),stat('Pages',pages.length),stat('Portfolio Items',pf.length),stat('Words Published',words)].join('');var hs=health(posts,pages);document.getElementById('dash-health').innerHTML=hs.length?hs.map(function(i){return item(i.t,i.d)}).join(''):item('All clear','No health issues found.');document.getElementById('dash-analytics').innerHTML=[item('Average words per post',posts.length?Math.round(words/posts.length):0),item('Posts with meta descriptions',posts.filter(function(p){return p.meta.description}).length+' of '+posts.length),item('Posts with social images',posts.filter(function(p){return p.meta.social_image}).length+' of '+posts.length)].join('');document.getElementById('dash-summary').innerHTML=[item('Latest post',posts[0]?(posts[0].meta.title||posts[0].name):'No posts yet'),item('Indexable pages',pages.filter(function(p){return p.meta.noindex!==true}).length),item('Tracked policy pages',pages.map(function(p){return p.key}).join(', '))].join('')}
    async function exportBackup(type){if(type==='posts'&&!postsHydratedAll){await ensurePostsHydrated(postsCache);postsHydratedAll=true}var payload;if(type==='posts')payload=postsCache.map(function(p){return{path:p.path,meta:p.meta,content:p.content}});else if(type==='portfolio')payload=portfolioCache;else if(type==='pages')payload=Object.keys(PAGE_FILES);else if(type==='settings')payload=siteCache;else payload={posts:postsCache,portfolio:portfolioCache,settings:siteCache,exportedAt:new Date().toISOString()};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='metaxenopy-'+type+'-backup.json';a.click();URL.revokeObjectURL(url)}
    function yamlVal(raw,key){var re=new RegExp('^'+key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+':\\s*"?([^"\\n]*)"?$','m'),m=raw.match(re);return m?m[1]:''}
    function yamlSet(raw,key,val){var re=new RegExp('^'+key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+':\\s*.*$','m'),line=key+': "'+String(val||'').replace(/"/g,'\\"')+'"';return re.test(raw)?raw.replace(re,line):raw.trimEnd()+'\n'+line+'\n'}
    function normalizePath(path){var value=String(path||'').trim();if(!value)return'';return value.charAt(0)==='/'?value:'/'+value}
    function cacheBust(path){var value=normalizePath(path);return value?resolvePath(value)+'?v='+Date.now():''}
    function setImagePreview(id,path){var img=document.getElementById(id);if(!img)return;img.src=path?cacheBust(path):'';img.classList.toggle('is-empty',!path)}
    function syncColorPreview(value){var dot=document.querySelector('.color-preview-dot');if(dot)dot.style.background=String(value||'').trim()||'#2563eb'}
    function previewSelectedFile(inputId,previewId){var input=document.getElementById(inputId),img=document.getElementById(previewId);if(!input||!img||!input.files||!input.files[0])return;img.src=URL.createObjectURL(input.files[0]);img.classList.remove('is-empty')}
    function imageExt(file){var name=(file&&file.name?file.name:'').toLowerCase(),match=name.match(/\.([a-z0-9]+)$/);return match?'.'+match[1]:''}
    function ensureImageFile(file,label,allowed){var ext=imageExt(file);if(!file)throw new Error('Select a '+label.toLowerCase()+' file first.');if(allowed&&allowed.indexOf(ext)===-1)throw new Error(label+' must use one of these file types: '+allowed.join(', ')+'.');if(file.size>8*1024*1024)throw new Error(label+' must be 8 MB or smaller.');return ext}
    async function saveConfigRaw(raw,message){await ghPutFile(CONFIG_FILE,raw,siteCache.configSha,message);var cfg=await ghGetFile(CONFIG_FILE);siteCache.configRaw=cfg.raw;siteCache.configSha=cfg.sha;return cfg.raw}
    function primaryBrandImagePath(){var cfg=configMap();return cfg.profile_image||'/assets/images/kenji-avatar-128.png'}
    function refreshBrandingPreviews(){var cfg=configMap(),shared=primaryBrandImagePath();setImagePreview('st-logo-preview',cfg.logo||'/assets/images/logo.png');setImagePreview('st-favicon-preview','/assets/images/favicon.ico');setImagePreview('st-profile-preview',shared)}
    async function prefillSettings(){var tok=load(KEY_TOKEN);if(tok)document.getElementById('st-token').value=tok;try{var cfg=await ghGetFile(CONFIG_FILE);siteCache.configRaw=cfg.raw;siteCache.configSha=cfg.sha;document.getElementById('st-verify').value=yamlVal(cfg.raw,'google_site_verification');document.getElementById('st-pub').value=yamlVal(cfg.raw,'google_adsense_publisher_id');document.getElementById('st-post-slot').value=yamlVal(cfg.raw,'google_adsense_post_slot_id');document.getElementById('st-head-slot').value=yamlVal(cfg.raw,'google_adsense_header_slot_id');document.getElementById('st-foot-slot').value=yamlVal(cfg.raw,'google_adsense_footer_slot_id');var robots=await ghGetFile(ROBOTS_FILE);siteCache.robotsRaw=robots.raw;siteCache.robotsSha=robots.sha;document.getElementById('st-robots').value=robots.raw;var ads=await ghGetFile(ADS_FILE);siteCache.adsRaw=ads.raw;siteCache.adsSha=ads.sha;document.getElementById('st-ads').value=ads.raw;var css=await ghGetFile('assets/css/main.css'),m=css.raw.match(/--color-primary:\s*([^;]+)/);if(m){document.getElementById('st-color').value=m[1].trim();document.getElementById('st-color-text').textContent=m[1].trim();syncColorPreview(m[1].trim())}refreshBrandingPreviews()}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    function saveToken(){var t=document.getElementById('st-token').value.trim();if(!t)return showAlert('settings-alert','error','Token cannot be empty.');store(KEY_TOKEN,t);showAlert('settings-alert','success','GitHub token saved.')}
    async function saveIntegrations(){try{var raw=siteCache.configRaw||(await ghGetFile(CONFIG_FILE)).raw;raw=yamlSet(raw,'google_site_verification',document.getElementById('st-verify').value.trim());raw=yamlSet(raw,'google_adsense_publisher_id',document.getElementById('st-pub').value.trim());raw=yamlSet(raw,'google_adsense_post_slot_id',document.getElementById('st-post-slot').value.trim());raw=yamlSet(raw,'google_adsense_header_slot_id',document.getElementById('st-head-slot').value.trim());raw=yamlSet(raw,'google_adsense_footer_slot_id',document.getElementById('st-foot-slot').value.trim());await saveConfigRaw(raw,'Update site integrations');showAlert('settings-alert','success','Search Console and AdSense settings saved.')}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    async function saveTextFiles(){try{await ghPutFile(ROBOTS_FILE,document.getElementById('st-robots').value,siteCache.robotsSha,'Update robots.txt');var r1=await ghGetFile(ROBOTS_FILE);siteCache.robotsSha=r1.sha;await ghPutFile(ADS_FILE,document.getElementById('st-ads').value,siteCache.adsSha,'Update ads.txt');var r2=await ghGetFile(ADS_FILE);siteCache.adsSha=r2.sha;showAlert('settings-alert','success','robots.txt and ads.txt saved.')}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    async function changePassword(){var oldp=document.getElementById('st-old').value,newp=document.getElementById('st-new').value,conf=document.getElementById('st-confirm').value;if(await sha256(oldp)!==load(KEY_HASH))return showAlert('settings-alert','error','Current password is incorrect.');if(!newp)return showAlert('settings-alert','error','New password is required.');if(newp!==conf)return showAlert('settings-alert','error','Passwords do not match.');store(KEY_HASH,await sha256(newp));createSession();showAlert('settings-alert','success','Password changed successfully.')}
    function resetAdmin(){if(!confirm('Reset locally stored admin credentials in this browser?'))return;[KEY_HASH,KEY_TOKEN,KEY_SESSION,KEY_SESSION_EXP,KEY_POST_AUTOSAVE].forEach(remove);logout()}
    async function updateTheme(){try{var color=document.getElementById('st-color').value,css=await ghGetFile('assets/css/main.css'),updated=css.raw.replace(/(--color-primary:\s*)[^;]+/,'$1'+color);await ghPutFile('assets/css/main.css',updated,css.sha,'Update theme colors');document.getElementById('st-color-text').textContent=color;showAlert('settings-alert','success','Theme color updated.')}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    async function uploadLogo(){try{var f=document.getElementById('st-logo').files[0],ext=ensureImageFile(f,'Logo',['.png','.jpg','.jpeg','.webp','.svg']),path='/assets/images/site-logo'+ext;await putBinary(f,path.slice(1),'Update logo');await saveConfigRaw(yamlSet(siteCache.configRaw,'logo',path),'Update logo setting');refreshBrandingPreviews();showAlert('settings-alert','success','Logo uploaded and applied site-wide.')}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    async function uploadFavicon(){try{var f=document.getElementById('st-favicon').files[0];ensureImageFile(f,'Favicon',['.ico']);await putBinary(f,'assets/images/favicon.ico','Update favicon');refreshBrandingPreviews();showAlert('settings-alert','success','Favicon uploaded.')}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    async function uploadProfileImage(){try{var f=document.getElementById('st-profile-image').files[0],ext=ensureImageFile(f,'Profile picture',['.png','.jpg','.jpeg','.webp']),path='/assets/images/profile-image'+ext,raw=yamlSet(siteCache.configRaw,'profile_image',path);await putBinary(f,path.slice(1),'Update profile image');await saveConfigRaw(raw,'Update profile image');refreshBrandingPreviews();showAlert('settings-alert','success','Profile picture uploaded and applied site-wide.')}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    function bind(el,eventName,handler){if(el)el.addEventListener(eventName,handler)}
    function renderAuthFallback(message){var box=document.getElementById('auth-content');if(!box)return;box.innerHTML='<div class="alert alert-error">'+esc(message||'Admin startup error. Reload the page and try again.')+'</div><div id="login-alert"></div><div class="fg"><label>Password</label><input type="password" id="login-pwd" data-enter-action="do-login"></div><button class="btn p full" type="button" data-action="do-login">Login</button>'}
    function runEditorCommand(editor,command,before,after,placeholder){if(editor==='page'){if(command==='wrap')insertPageWrap(before,after,placeholder);else if(command==='line')insertPageLine(before,placeholder);else if(command==='block')insertAtCursor(getPgEd(),before+placeholder+after),refreshPagePreview()}else{if(command==='wrap')insertWrap(before,after,placeholder);else if(command==='line')insertLine(before,placeholder);else if(command==='block')insertBlock(before,placeholder,after)}}
    function runAction(action,target){if(action==='show-section')showSection(target.getAttribute('data-section'));else if(action==='logout')logout();else if(action==='refresh-dashboard')refreshDashboard();else if(action==='export-backup')exportBackup(target.getAttribute('data-export-type'));else if(action==='open-post-editor')openPostEditor();else if(action==='edit-post')editPost(target.getAttribute('data-path'));else if(action==='remove-post')removePost(target.getAttribute('data-path'));else if(action==='posts-page')changePostsPage(target.getAttribute('data-page'));else if(action==='save-post')savePost();else if(action==='apply-template')applyTemplate(target.getAttribute('data-template'));else if(action==='upload-editor-media')uploadEditorMedia();else if(action==='editor-command')runEditorCommand(target.getAttribute('data-editor'),target.getAttribute('data-command'),target.getAttribute('data-before')||'',target.getAttribute('data-after')||'',target.getAttribute('data-placeholder')||'');else if(action==='open-portfolio-editor'){var index=target.getAttribute('data-index');openPortfolioEditor(index===null||index===''?null:Number(index))}else if(action==='move-portfolio')movePf(Number(target.getAttribute('data-index')),Number(target.getAttribute('data-direction')));else if(action==='remove-portfolio')removePf(Number(target.getAttribute('data-index')));else if(action==='remove-pf-tag')removePfTag(Number(target.getAttribute('data-index')));else if(action==='save-portfolio-item')savePortfolioItem();else if(action==='open-page-editor')openPageEditor(target.getAttribute('data-page'));else if(action==='save-page')savePage();else if(action==='upload-media')uploadMedia();else if(action==='load-media')loadMedia();else if(action==='copy-media-markdown')copyText(target.getAttribute('data-markdown'));else if(action==='copy-media-path')copyText(target.getAttribute('data-path'));else if(action==='save-token')saveToken();else if(action==='save-integrations')saveIntegrations();else if(action==='save-text-files')saveTextFiles();else if(action==='upload-logo')uploadLogo();else if(action==='upload-favicon')uploadFavicon();else if(action==='upload-profile-image')uploadProfileImage();else if(action==='update-theme')updateTheme();else if(action==='change-password')changePassword();else if(action==='reset-admin')resetAdmin();else if(action==='do-setup')doSetup();else if(action==='do-login')doLogin()}
    function registerDelegatedEvents(){document.addEventListener('click',function(event){var target=event.target.closest('[data-action]');if(!target)return;event.preventDefault();runAction(target.getAttribute('data-action'),target)});document.addEventListener('keydown',function(event){var target=event.target;if(target&&target.id==='pf-tags'){pfTagKey(event);return}if(target&&(target.id==='pe-content'||target.id==='pg-content')){tabKey(event);return}if(target&&target.hasAttribute&&target.hasAttribute('data-enter-action')&&event.key==='Enter'){event.preventDefault();runAction(target.getAttribute('data-enter-action'),target);return}var pageTrigger=target&&target.closest?target.closest('[data-action="open-page-editor"]'):null;if(pageTrigger&&(event.key==='Enter'||event.key===' ')){event.preventDefault();runAction('open-page-editor',pageTrigger)}})}
    function registerResponsiveNav(){var els=navEls();if(!els.toggle||!els.nav)return;bind(els.toggle,'click',function(){setNavMenuOpen(els.toggle.getAttribute('aria-expanded')!=='true')});bind(window,'resize',syncNavMenu);document.addEventListener('keydown',function(event){if(event.key==='Escape'&&!isDesktopNav()){closeNavMenu();els.toggle.focus()}});syncNavMenu()}
    function bindStaticInputs(){bind(document.getElementById('post-search'),'input',onPostFiltersChanged);bind(document.getElementById('post-filter'),'change',onPostFiltersChanged);bind(document.getElementById('pe-status'),'change',onPostStatus);bind(document.getElementById('pe-title'),'input',syncPostEditor);bind(document.getElementById('pe-date'),'change',syncPostEditor);bind(document.getElementById('pe-file'),'input',syncPostEditor);['pe-cats','pe-tags','pe-youtube','pe-desc','pe-social','pe-canonical'].forEach(function(id){bind(document.getElementById(id),'input',updatePostChecklist)});bind(document.getElementById('pe-content'),'input',function(){refreshPostPreview();updatePostChecklist()});bind(document.getElementById('pg-title'),'input',function(){syncPageField('title')});bind(document.getElementById('pg-desc'),'input',function(){syncPageField('description')});bind(document.getElementById('pg-seo'),'input',function(){syncPageField('seo_title')});bind(document.getElementById('pg-social'),'input',function(){syncPageField('social_image')});bind(document.getElementById('pg-canonical'),'input',function(){syncPageField('canonical_url')});bind(document.getElementById('pg-permalink'),'input',function(){syncPageField('permalink')});bind(document.getElementById('pg-noindex'),'change',function(){syncPageField('noindex')});bind(document.getElementById('pg-content'),'input',function(){refreshPagePreview();updatePageChecks()});bind(document.getElementById('pf-tags-box'),'click',function(){document.getElementById('pf-tags').focus()});bind(document.getElementById('st-color'),'input',function(){document.getElementById('st-color-text').textContent=this.value;syncColorPreview(this.value)});['st-logo','st-favicon'].forEach(function(id){bind(document.getElementById(id),'change',function(){var previewMap={'st-logo':'st-logo-preview','st-favicon':'st-favicon-preview'};previewSelectedFile(id,previewMap[id])})});bind(document.getElementById('st-profile-image'),'change',function(){previewSelectedFile('st-profile-image','st-profile-preview')})}
    function copyText(t){navigator.clipboard.writeText(t).then(function(){showAlert('media-alert','success','Copied to clipboard.')}).catch(function(){})}
    function bootAdmin(){try{initAuth()}catch(err){console.error('Admin auth initialization failed:',err);renderAuthFallback('Admin startup error while loading the login panel.')}try{bindStaticInputs();registerDelegatedEvents();registerResponsiveNav()}catch(err){console.error('Admin interface boot error:',err);if(!document.getElementById('auth-content').innerHTML.trim())renderAuthFallback('Admin startup error while preparing the interface.')}try{if(isAuthenticated())enterAdmin()}catch(err){console.error('Admin session restore error:',err);logout();renderAuthFallback('Saved admin session could not be restored. Please log in again.')}} 
    document.addEventListener('DOMContentLoaded',bootAdmin)
