'use strict';
    var REPO_OWNER='darzmackz',REPO_NAME='darzmackz.github.io',REPO_BRANCH='main',POSTS_DIR='_posts',PORTFOLIO_FILE='_data/portfolio.json',CONFIG_FILE='_config.yml',ROBOTS_FILE='robots.txt',ADS_FILE='ads.txt',MEDIA_DIR='assets/images';
    var PAGE_FILES={home:'index.html',about:'about.md',contact:'contact.md',privacy:'privacy.md',disclosure:'disclosure.md'};
    var TIMEZONE_OFFSET='+0800',SESSION_TTL_MS=7*24*3600*1000,KEY_HASH='admin_pwd_hash',KEY_TOKEN='admin_github_token',KEY_SESSION='admin_session',KEY_SESSION_EXP='admin_session_exp',KEY_POST_AUTOSAVE='post_editor_autosave_v2';
    var sections=['dashboard','posts','post-editor','portfolio','portfolio-editor','pages','page-editor','media','settings'],postsCache=[],portfolioCache=[],portfolioSha=null,pfTech=[],currentPf=null,currentPost=null,currentPage=null,siteCache={configRaw:'',configSha:null,robotsRaw:'',robotsSha:null,adsRaw:'',adsSha:null};
    var templates={lyrics:{title:'Song Title Lyrics and Karaoke Guide',categories:'music, lyrics, karaoke',tags:'lyrics, karaoke, music',excerpt:'A clear and useful introduction to the song, lyrics, and karaoke angle.',content:'## Song Overview\n\nIntroduce the track and why it matters.\n\n## Lyrics and Karaoke Notes\n\n- standout lyric themes\n- sing-along moments\n- audience appeal\n\n## Final Thoughts\n\nWrap up with a short takeaway.\n'},music:{title:'Artist or Track Feature',categories:'music, feature',tags:'music, artist-feature',excerpt:'A short feature highlighting the track, performance, or artist perspective.',content:'## What Makes This Stand Out\n\nDescribe the performance, release, or audience appeal.\n\n## Why It Connects With Listeners\n\nShare what works well and why.\n\n## Final Thoughts\n\nClose with a short takeaway.\n'},tech:{title:'Practical Tech Walkthrough',categories:'tutorial, tech',tags:'tech, tutorial',excerpt:'A practical technical walkthrough with clear steps and a useful outcome.',content:'## Problem\n\nDescribe the issue or goal.\n\n## Solution\n\nExplain the approach and key steps.\n\n## Notes\n\n- best practices\n- caveats\n- follow-up ideas\n'}};
    function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
    function escJs(s){return String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'")}
    function store(k,v){try{localStorage.setItem(k,v)}catch(e){}}
    function load(k){try{return localStorage.getItem(k)}catch(e){return null}}
    function remove(k){try{localStorage.removeItem(k)}catch(e){}}
    function showAlert(id,t,m){var e=document.getElementById(id);if(!e)return;e.innerHTML='<div class="alert alert-'+t+'">'+m+'</div>';setTimeout(function(){if(e)e.innerHTML=''},6000)}
    async function sha256(msg){var b=new TextEncoder().encode(msg),h=await crypto.subtle.digest('SHA-256',b);return Array.from(new Uint8Array(h)).map(function(x){return x.toString(16).padStart(2,'0')}).join('')}
    function randomToken(){var a=new Uint8Array(32);crypto.getRandomValues(a);return Array.from(a).map(function(b){return b.toString(16).padStart(2,'0')}).join('')}
    function createSession(){var t=randomToken();store(KEY_SESSION,t);store(KEY_SESSION_EXP,String(Date.now()+SESSION_TTL_MS));return t}
    function isAuthenticated(){var s=load(KEY_SESSION),e=load(KEY_SESSION_EXP),h=load(KEY_HASH);if(!s||!e||!h)return false;if(Date.now()>Number(e)){remove(KEY_SESSION);remove(KEY_SESSION_EXP);return false}return true}
    function today(){var d=new Date();return[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
    function slugify(t){return String(t||'').toLowerCase().replace(/[^\w\s-]/g,'').replace(/[\s_]+/g,'-').replace(/-+/g,'-').replace(/^-+|-+$/g,'')}
    function decode64(b){var bytes=Uint8Array.from(atob(b.replace(/\n/g,'')),function(c){return c.charCodeAt(0)});return new TextDecoder().decode(bytes)}
    function encode64(c){var bytes=new TextEncoder().encode(c),bin='';for(var i=0;i<bytes.length;i++)bin+=String.fromCharCode(bytes[i]);return btoa(bin)}
    function parseFM(raw){var m=raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);if(!m)return{meta:{},content:raw};var meta={};m[1].split(/\r?\n/).forEach(function(line){if(!line.trim())return;var i=line.indexOf(':');if(i===-1)return;var k=line.slice(0,i).trim(),v=line.slice(i+1).trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);if(v==='true')v=true;else if(v==='false')v=false;else if(v.startsWith('[')&&v.endsWith(']'))v=v.slice(1,-1).split(',').map(function(s){return s.trim().replace(/^['"]|['"]$/g,'')}).filter(Boolean);meta[k]=v});return{meta:meta,content:m[2].replace(/^\n+/,'')}}
    function fmVal(v){if(v===true||v===false)return String(v);if(Array.isArray(v))return'['+v.join(', ')+']';return'"'+String(v).replace(/"/g,'\\"')+'"'}
    function buildFM(meta,layout){var l=['---','layout: '+(layout||meta.layout||'post')];Object.keys(meta).forEach(function(k){if(k==='layout')return;var v=meta[k];if(v===''||v===null||typeof v==='undefined')return;l.push(k+': '+fmVal(v))});l.push('---');return l.join('\n')}
    async function ghRequest(method,path,body){var token=load(KEY_TOKEN);if(!token)throw new Error('No GitHub token. Go to Settings and add your token.');var res=await fetch('https://api.github.com/repos/'+REPO_OWNER+'/'+REPO_NAME+'/contents/'+path,{method:method,headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github.v3+json','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!res.ok){var err=await res.json().catch(function(){return{message:res.statusText}});throw new Error(err.message||('GitHub API error: '+res.status))}return res.status===204?null:res.json()}
    async function ghGetFile(path){var f=await ghRequest('GET',path);return{raw:decode64(f.content),sha:f.sha,path:path}}
    async function ghPutFile(path,content,sha,message){var body={message:message,content:encode64(content),branch:REPO_BRANCH};if(sha)body.sha=sha;return ghRequest('PUT',path,body)}
    async function ghPut64(path,b64,sha,message){var body={message:message,content:b64,branch:REPO_BRANCH};if(sha)body.sha=sha;return ghRequest('PUT',path,body)}
    async function ghDelete(path,sha,message){return ghRequest('DELETE',path,{message:message,sha:sha,branch:REPO_BRANCH})}
    async function ghList(path){var r=await ghRequest('GET',path);return Array.isArray(r)?r:[]}
    async function initAuth(){var box=document.getElementById('auth-content');if(!load(KEY_HASH)){box.innerHTML='<div class="alert alert-info"><strong>First-time setup</strong><br>Set a password and add your GitHub token.</div><div id="setup-alert"></div><div class="fg"><label>Admin Password</label><input type="password" id="setup-pwd"></div><div class="fg"><label>Confirm Password</label><input type="password" id="setup-confirm"></div><div class="fg"><label>GitHub Personal Access Token</label><input type="password" id="setup-token" placeholder="ghp_..."></div><button class="btn p full" onclick="doSetup()">Set Up Admin Panel</button>'}else{box.innerHTML='<div id="login-alert"></div><div class="fg"><label>Password</label><input type="password" id="login-pwd" onkeydown="if(event.key===\'Enter\'){doLogin();}"></div><button class="btn p full" onclick="doLogin()">Login</button>'}}
    async function doSetup(){var p=document.getElementById('setup-pwd').value,c=document.getElementById('setup-confirm').value,t=document.getElementById('setup-token').value.trim();if(!p)return showAlert('setup-alert','error','Password is required.');if(p!==c)return showAlert('setup-alert','error','Passwords do not match.');if(!t)return showAlert('setup-alert','error','GitHub token is required.');store(KEY_HASH,await sha256(p));store(KEY_TOKEN,t);createSession();enterAdmin()}
    async function doLogin(){var p=document.getElementById('login-pwd').value;if(!p)return showAlert('login-alert','error','Enter your password.');if(await sha256(p)!==load(KEY_HASH))return showAlert('login-alert','error','Incorrect password.');createSession();enterAdmin()}
    function logout(){remove(KEY_SESSION);remove(KEY_SESSION_EXP);document.getElementById('admin-view').classList.add('hidden');document.getElementById('auth-view').classList.remove('hidden');initAuth()}
    function setNav(name){['dashboard','posts','portfolio','pages','media','settings'].forEach(function(id){var el=document.getElementById('nav-'+id);if(!el)return;el.classList.toggle('p',id===name);el.classList.toggle('g',id!==name)})}
    function enterAdmin(){document.getElementById('auth-view').classList.add('hidden');document.getElementById('admin-view').classList.remove('hidden');showSection(load('admin_last_section')||'dashboard')}
    function showSection(name){sections.forEach(function(s){var el=document.getElementById('sec-'+s);if(el)el.classList.add('hidden')});var cur=document.getElementById('sec-'+name);if(cur)cur.classList.remove('hidden');store('admin_last_section',name);if(['dashboard','posts','portfolio','pages','media','settings'].indexOf(name)!==-1)setNav(name);if(name==='dashboard')refreshDashboard();if(name==='posts')loadPosts();if(name==='portfolio')loadPortfolio();if(name==='media')loadMedia();if(name==='settings')prefillSettings()}
    function postStatus(meta){var d=String(meta.date||today()).slice(0,10);if(meta.status==='draft'||meta.published===false)return'draft';if(meta.status==='scheduled'||d>today())return'scheduled';return'published'}
    function statusPill(s){return'<span class="pill '+s+'">'+esc(s.charAt(0).toUpperCase()+s.slice(1))+'</span>'}
    function postUrl(name){var c=String(name).replace('.md',''),dp=c.slice(0,10).split('-'),slug=c.slice(11);return'/'+dp.join('/')+'/'+slug+'/'}
    async function loadPosts(){var wrap=document.getElementById('posts-wrap');wrap.innerHTML='<div class="loading"><span class="spin"></span> Loading posts...</div>';try{var files=await ghList(POSTS_DIR);var posts=files.filter(function(f){return f.name.endsWith('.md')});for(var i=0;i<posts.length;i++){var full=await ghGetFile(posts[i].path);posts[i].raw=full.raw;posts[i].sha=full.sha;var p=parseFM(full.raw);posts[i].meta=p.meta;posts[i].content=p.content;posts[i].status=postStatus(p.meta)}postsCache=posts.sort(function(a,b){return String(b.meta.date||'').localeCompare(String(a.meta.date||''))});renderPostsList()}catch(err){wrap.innerHTML='<div class="alert alert-error">'+esc(err.message)+'</div>'}}
    function renderPostsList(){var wrap=document.getElementById('posts-wrap'),q=(document.getElementById('post-search').value||'').toLowerCase(),f=document.getElementById('post-filter').value;var items=postsCache.filter(function(p){var hay=((p.meta.title||'')+' '+p.name).toLowerCase();return(!q||hay.indexOf(q)!==-1)&&(f==='all'||p.status===f)});if(!items.length){wrap.innerHTML='<div class="card"><p class="muted">No posts match the current filters.</p></div>';return}wrap.innerHTML='<div class="posts">'+items.map(function(p){return'<div class="post"><div class="info"><div class="title">'+esc(p.meta.title||p.name)+' '+statusPill(p.status)+'</div><div class="meta">'+esc(String(p.meta.date||'').slice(0,10))+' | '+esc(p.name)+' | <a href="'+esc(postUrl(p.name))+'" target="_blank" rel="noopener">View</a></div></div><div class="actions"><button class="btn sm" onclick="editPost(\''+escJs(p.path)+'\')">Edit</button><button class="btn d sm" onclick="removePost(\''+escJs(p.path)+'\')">Delete</button></div></div>'}).join('')+'</div>'}
    function postValues(){return{title:document.getElementById('pe-title').value.trim(),date:document.getElementById('pe-date').value||today(),categories:document.getElementById('pe-cats').value.trim(),tags:document.getElementById('pe-tags').value.trim(),youtube:document.getElementById('pe-youtube').value.trim(),desc:document.getElementById('pe-desc').value.trim(),seoTitle:document.getElementById('pe-seo-title').value.trim(),social:document.getElementById('pe-social').value.trim(),canonical:document.getElementById('pe-canonical').value.trim(),file:document.getElementById('pe-file').value.trim(),content:document.getElementById('pe-content').value,status:document.getElementById('pe-status').value}}
    function setPostValues(v){v=v||{title:'',date:today(),categories:'',tags:'',youtube:'',desc:'',seoTitle:'',social:'',canonical:'',file:'',content:'',status:'published'};document.getElementById('pe-title').value=v.title||'';document.getElementById('pe-date').value=v.date||today();document.getElementById('pe-cats').value=v.categories||'';document.getElementById('pe-tags').value=v.tags||'';document.getElementById('pe-youtube').value=v.youtube||'';document.getElementById('pe-desc').value=v.desc||'';document.getElementById('pe-seo-title').value=v.seoTitle||'';document.getElementById('pe-social').value=v.social||'';document.getElementById('pe-canonical').value=v.canonical||'';document.getElementById('pe-file').value=v.file||'';document.getElementById('pe-content').value=v.content||'';document.getElementById('pe-status').value=v.status||'published';document.getElementById('pe-template').value='';syncPostEditor()}
    function openPostEditor(){currentPost=null;document.getElementById('post-editor-title').textContent='New Post';showSection('post-editor');var a=load(KEY_POST_AUTOSAVE);if(a){try{return setPostValues(JSON.parse(a))}catch(e){}}setPostValues()}
    async function editPost(path){try{var f=await ghGetFile(path),p=parseFM(f.raw);currentPost={path:path,sha:f.sha,file:path.split('/').pop()};document.getElementById('post-editor-title').textContent='Edit Post';showSection('post-editor');setPostValues({title:p.meta.title||'',date:String(p.meta.date||today()).slice(0,10),categories:Array.isArray(p.meta.categories)?p.meta.categories.join(', '):String(p.meta.categories||'').replace(/[\[\]]/g,''),tags:Array.isArray(p.meta.tags)?p.meta.tags.join(', '):String(p.meta.tags||'').replace(/[\[\]]/g,''),youtube:p.meta.youtube_id||'',desc:p.meta.description||'',seoTitle:p.meta.seo_title||'',social:p.meta.social_image||'',canonical:p.meta.canonical_url||'',file:currentPost.file,content:p.content,status:postStatus(p.meta)})}catch(err){showAlert('posts-wrap','error',esc(err.message))}}
    function applyTemplate(name){var t=templates[name],v=postValues();if(!t)return;if(!v.title)document.getElementById('pe-title').value=t.title;if(!v.categories)document.getElementById('pe-cats').value=t.categories;if(!v.tags)document.getElementById('pe-tags').value=t.tags;if(!v.desc)document.getElementById('pe-desc').value=t.excerpt;if(!v.content.trim())document.getElementById('pe-content').value=t.content;syncPostEditor()}
    function onPostStatus(){if(document.getElementById('pe-status').value==='scheduled'&&document.getElementById('pe-date').value<=today()){var d=new Date();d.setDate(d.getDate()+2);document.getElementById('pe-date').value=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}syncPostEditor()}
    function syncPostEditor(){var v=postValues(),file=v.file||(v.date+'-'+slugify(v.title)+'.md');document.getElementById('pe-slug').textContent=postUrl(file);store(KEY_POST_AUTOSAVE,JSON.stringify(v));refreshPostPreview();updatePostChecklist()}
    function refreshPostPreview(){document.getElementById('post-preview').innerHTML=md(document.getElementById('pe-content').value);store(KEY_POST_AUTOSAVE,JSON.stringify(postValues()))}
    function updatePostChecklist(){var v=postValues(),checks=[{ok:!!v.title,text:'Title is filled in.'},{ok:v.desc.length>=50,text:'Meta description is descriptive (50+ characters).'},{ok:v.content.trim().split(/\s+/).filter(Boolean).length>=120,text:'Content has at least 120 words.'},{ok:!!v.categories,text:'Categories are present.'},{ok:!!v.tags,text:'Tags are present.'},{ok:!v.social||v.social.indexOf('/assets/images/')===0||v.social.indexOf('http')===0,text:'Social image path looks valid.'},{ok:!v.canonical||/^https?:\/\//.test(v.canonical),text:'Canonical URL is absolute when provided.'},{ok:v.status!=='scheduled'||v.date>today(),text:'Scheduled posts use a future date.'}];document.getElementById('post-checks').innerHTML=checks.map(function(c){return'<div class="check '+(c.ok?'pass':'warn')+'">'+(c.ok?'&#10003;':'&#9888;')+' '+esc(c.text)+'</div>'}).join('')}
    async function savePost(){var v=postValues();if(!v.title)return showAlert('post-editor-alert','error','Title is required.');var file=v.file||(v.date+'-'+slugify(v.title)+'.md');if(!/\.md$/i.test(file))file+='.md';var path=POSTS_DIR+'/'+file;if(!currentPost){try{await ghGetFile(path);return showAlert('post-editor-alert','error','A post with this filename already exists.')}catch(e){}}var meta={title:v.title,date:v.date+' 12:00:00 '+TIMEZONE_OFFSET,categories:v.categories?v.categories.split(',').map(function(s){return s.trim()}).filter(Boolean):[],tags:v.tags?v.tags.split(',').map(function(s){return s.trim()}).filter(Boolean):[],youtube_id:v.youtube||'',description:v.desc||'',seo_title:v.seoTitle||'',social_image:v.social||'',canonical_url:v.canonical||'',status:v.status,published:v.status!=='draft'};var full=buildFM(meta,'post')+'\n\n'+v.content.trim()+'\n',btn=document.getElementById('save-post-btn');btn.disabled=true;btn.innerHTML='<span class="spin"></span> Saving...';try{await ghPutFile(path,full,currentPost?currentPost.sha:null,currentPost?'Update: '+v.title:'Add: '+v.title);var r=await ghGetFile(path);currentPost={path:path,sha:r.sha,file:file};document.getElementById('pe-file').value=file;showAlert('post-editor-alert','success','Post saved. GitHub Pages will rebuild shortly.');await loadPosts()}catch(err){showAlert('post-editor-alert','error',esc(err.message))}finally{btn.disabled=false;btn.textContent='Save Post'}}
    async function removePost(path){var p=postsCache.find(function(x){return x.path===path});if(!p||!confirm('Delete "'+(p.meta.title||p.name)+'"?'))return;try{await ghDelete(p.path,p.sha,'Delete: '+p.name);await loadPosts()}catch(err){alert('Error: '+err.message)}}
    async function loadPortfolio(){var wrap=document.getElementById('portfolio-wrap');wrap.innerHTML='<div class="loading"><span class="spin"></span> Loading portfolio...</div>';try{var r=await ghGetFile(PORTFOLIO_FILE);portfolioSha=r.sha;portfolioCache=JSON.parse(r.raw);if(!portfolioCache.length){wrap.innerHTML='<div class="card"><p class="muted">No portfolio items yet.</p></div>';return}wrap.innerHTML='<div class="portfolio">'+portfolioCache.map(function(item,i){var badges=(item.tech||[]).map(function(t){return'<span class="pill">'+esc(t)+'</span>'}).join(' ');return'<div class="pf"><div style="font-size:28px">'+esc(item.icon||'📌')+'</div><div class="info"><div class="title">'+esc(item.title)+'</div><div class="meta">'+badges+'</div></div><div class="actions"><button class="btn sm" onclick="movePf('+i+',-1)">↑</button><button class="btn sm" onclick="movePf('+i+',1)">↓</button><button class="btn sm" onclick="openPortfolioEditor('+i+')">Edit</button><button class="btn d sm" onclick="removePf('+i+')">Delete</button></div></div>'}).join('')+'</div>'}catch(err){wrap.innerHTML='<div class="alert alert-error">'+esc(err.message)+'</div>'}}
    function openPortfolioEditor(i){currentPf=i;pfTech=[];if(i!==null&&typeof i!=='undefined'){var item=portfolioCache[i];document.getElementById('pf-editor-title').textContent='Edit Portfolio Item';document.getElementById('pf-icon').value=item.icon||'';document.getElementById('pf-title').value=item.title||'';document.getElementById('pf-subtitle').value=item.subtitle||'';document.getElementById('pf-description').value=item.description||'';document.getElementById('pf-link').value=item.link||'';document.getElementById('pf-link-text').value=item.link_text||'';pfTech=Array.isArray(item.tech)?item.tech.slice():[]}else{document.getElementById('pf-editor-title').textContent='New Portfolio Item';['pf-icon','pf-title','pf-subtitle','pf-description','pf-link','pf-link-text'].forEach(function(id){document.getElementById(id).value=''})}renderPfTags();showSection('portfolio-editor')}
    function renderPfTags(){var box=document.getElementById('pf-tags-box'),input=document.getElementById('pf-tags');Array.from(box.querySelectorAll('.chip')).forEach(function(c){c.remove()});pfTech.forEach(function(tag,i){var chip=document.createElement('span');chip.className='chip';chip.innerHTML=esc(tag)+' <button onclick="removePfTag('+i+')">&times;</button>';box.insertBefore(chip,input)})}
    function addPfTag(v){v=v.trim();if(v&&pfTech.indexOf(v)===-1){pfTech.push(v);renderPfTags()}}
    function removePfTag(i){pfTech.splice(i,1);renderPfTags()}
    function pfTagKey(e){var input=document.getElementById('pf-tags');if(e.key==='Enter'||e.key===','){e.preventDefault();addPfTag(input.value.replace(/,/g,''));input.value=''}else if(e.key==='Backspace'&&input.value===''&&pfTech.length){pfTech.pop();renderPfTags()}}
    async function savePortfolioItem(){var title=document.getElementById('pf-title').value.trim();if(!title)return showAlert('pf-editor-alert','error','Title is required.');var part=document.getElementById('pf-tags').value.trim();if(part){addPfTag(part);document.getElementById('pf-tags').value=''}var item={id:slugify(title),icon:document.getElementById('pf-icon').value.trim()||'📌',title:title,subtitle:document.getElementById('pf-subtitle').value.trim(),description:document.getElementById('pf-description').value.trim(),tech:pfTech.slice(),link:document.getElementById('pf-link').value.trim(),link_text:document.getElementById('pf-link-text').value.trim()};if(currentPf===null||typeof currentPf==='undefined')portfolioCache.push(item);else portfolioCache[currentPf]=item;var btn=document.getElementById('save-pf-btn');btn.disabled=true;btn.innerHTML='<span class="spin"></span> Saving...';try{await ghPutFile(PORTFOLIO_FILE,JSON.stringify(portfolioCache,null,2)+'\n',portfolioSha,(currentPf===null||typeof currentPf==='undefined'?'Add portfolio item: ':'Update portfolio item: ')+title);var r=await ghGetFile(PORTFOLIO_FILE);portfolioSha=r.sha;portfolioCache=JSON.parse(r.raw);showAlert('pf-editor-alert','success','Portfolio item saved.')}catch(err){showAlert('pf-editor-alert','error',esc(err.message))}finally{btn.disabled=false;btn.textContent='Save Item'}}
    async function removePf(i){var item=portfolioCache[i];if(!item||!confirm('Delete "'+item.title+'"?'))return;portfolioCache.splice(i,1);try{await ghPutFile(PORTFOLIO_FILE,JSON.stringify(portfolioCache,null,2)+'\n',portfolioSha,'Delete portfolio item: '+item.title);var r=await ghGetFile(PORTFOLIO_FILE);portfolioSha=r.sha;portfolioCache=JSON.parse(r.raw);loadPortfolio()}catch(err){alert('Error: '+err.message)}}
    async function movePf(i,d){var n=i+d;if(n<0||n>=portfolioCache.length)return;var t=portfolioCache[i];portfolioCache[i]=portfolioCache[n];portfolioCache[n]=t;try{await ghPutFile(PORTFOLIO_FILE,JSON.stringify(portfolioCache,null,2)+'\n',portfolioSha,'Reorder portfolio items');var r=await ghGetFile(PORTFOLIO_FILE);portfolioSha=r.sha;portfolioCache=JSON.parse(r.raw);loadPortfolio()}catch(err){alert('Error: '+err.message)}}
    async function openPageEditor(key){currentPage={key:key,path:PAGE_FILES[key],sha:null,meta:{},layout:'page'};document.getElementById('page-editor-title').textContent='Edit '+key.charAt(0).toUpperCase()+key.slice(1)+' Page';showSection('page-editor');try{var f=await ghGetFile(currentPage.path),p=parseFM(f.raw);currentPage.sha=f.sha;currentPage.meta=p.meta;currentPage.layout=p.meta.layout||'page';document.getElementById('pg-title').value=p.meta.title||'';document.getElementById('pg-desc').value=p.meta.description||'';document.getElementById('pg-seo').value=p.meta.seo_title||'';document.getElementById('pg-social').value=p.meta.social_image||'';document.getElementById('pg-canonical').value=p.meta.canonical_url||'';document.getElementById('pg-permalink').value=p.meta.permalink||'';document.getElementById('pg-noindex').checked=p.meta.noindex===true;document.getElementById('pg-content').value=p.content;refreshPagePreview();updatePageChecks()}catch(err){showAlert('page-editor-alert','error',esc(err.message))}}
    function syncPageField(k){if(!currentPage)return;var map={title:'pg-title',description:'pg-desc',seo_title:'pg-seo',social_image:'pg-social',canonical_url:'pg-canonical',permalink:'pg-permalink',noindex:'pg-noindex'},el=document.getElementById(map[k]);currentPage.meta[k]=el.type==='checkbox'?el.checked:el.value.trim();updatePageChecks()}
    function refreshPagePreview(){document.getElementById('page-preview').innerHTML=md(document.getElementById('pg-content').value)}
    function updatePageChecks(){var c=document.getElementById('pg-content').value||'',checks=[{ok:!!document.getElementById('pg-title').value.trim(),text:'Title is set.'},{ok:document.getElementById('pg-desc').value.trim().length>=40,text:'Description is present and descriptive.'},{ok:c.trim().split(/\s+/).filter(Boolean).length>=80,text:'Page content has at least 80 words.'},{ok:!document.getElementById('pg-canonical').value.trim()||/^https?:\/\//.test(document.getElementById('pg-canonical').value.trim()),text:'Canonical URL is absolute when provided.'}];document.getElementById('page-checks').innerHTML=checks.map(function(x){return'<div class="check '+(x.ok?'pass':'warn')+'">'+(x.ok?'&#10003;':'&#9888;')+' '+esc(x.text)+'</div>'}).join('')}
    async function savePage(){if(!currentPage)return;var meta=Object.assign({},currentPage.meta,{title:document.getElementById('pg-title').value.trim(),description:document.getElementById('pg-desc').value.trim(),seo_title:document.getElementById('pg-seo').value.trim(),social_image:document.getElementById('pg-social').value.trim(),canonical_url:document.getElementById('pg-canonical').value.trim(),permalink:document.getElementById('pg-permalink').value.trim(),noindex:document.getElementById('pg-noindex').checked}),full=buildFM(meta,currentPage.layout)+'\n\n'+document.getElementById('pg-content').value.trim()+'\n',btn=document.getElementById('save-page-btn');btn.disabled=true;btn.innerHTML='<span class="spin"></span> Saving...';try{await ghPutFile(currentPage.path,full,currentPage.sha,'Update '+currentPage.path);var r=await ghGetFile(currentPage.path);currentPage.sha=r.sha;showAlert('page-editor-alert','success','Page saved.')}catch(err){showAlert('page-editor-alert','error',esc(err.message))}finally{btn.disabled=false;btn.textContent='Save Page'}}
    function file64(file){return new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(e){resolve(e.target.result.split(',')[1])};r.onerror=reject;r.readAsDataURL(file)})}
    async function putBinary(file,path,message){var b64=await file64(file),sha=null;try{sha=(await ghGetFile(path)).sha}catch(e){}return ghPut64(path,b64,sha,message)}
    async function loadMedia(){var wrap=document.getElementById('media-wrap');wrap.innerHTML='<div class="loading"><span class="spin"></span> Loading media...</div>';try{var files=await ghList(MEDIA_DIR);files=files.filter(function(f){return /\.(png|jpe?g|gif|svg|webp|ico)$/i.test(f.name)});if(!files.length){wrap.innerHTML='<div class="card"><p class="muted">No media files found yet.</p></div>';return}wrap.innerHTML=files.map(function(f){var path='/'+MEDIA_DIR+'/'+f.name;return'<div class="mitem"><img src="'+esc(path)+'" alt="'+esc(f.name)+'"><div class="muted" style="margin-bottom:8px">'+esc(f.name)+'</div><div class="stack"><button class="btn sm" onclick="copyText(\'!['+escJs(f.name)+']('+escJs(path)+')\')">Copy Markdown</button><button class="btn sm" onclick="copyText(\''+escJs(path)+'\')">Copy Path</button></div></div>'}).join('')}catch(err){wrap.innerHTML='<div class="alert alert-error">'+esc(err.message)+'</div>'}}
    async function uploadMedia(){var files=document.getElementById('media-upload').files;if(!files||!files.length)return showAlert('media-alert','error','Select one or more images first.');for(var i=0;i<files.length;i++)await putBinary(files[i],MEDIA_DIR+'/'+files[i].name,'Upload media: '+files[i].name);document.getElementById('media-upload').value='';showAlert('media-alert','success','Media upload complete.');loadMedia()}
    async function uploadEditorMedia(){var input=document.getElementById('pe-media'),file=input.files[0];if(!file)return showAlert('post-editor-alert','error','Select an image first.');await putBinary(file,MEDIA_DIR+'/'+file.name,'Upload media: '+file.name);insertAtCursor(document.getElementById('pe-content'),'!['+file.name+'](/'+MEDIA_DIR+'/'+file.name+')');input.value='';refreshPostPreview();updatePostChecklist();showAlert('post-editor-alert','success','Image uploaded and inserted into the post.')}
    function getEd(){return document.getElementById('pe-content')} function getPgEd(){return document.getElementById('pg-content')} function insertAtCursor(ta,text){var s=ta.selectionStart,e=ta.selectionEnd;ta.value=ta.value.slice(0,s)+text+ta.value.slice(e);ta.focus();ta.selectionStart=ta.selectionEnd=s+text.length}
    function insertWrap(b,a,p){var ta=getEd(),sel=ta.value.slice(ta.selectionStart,ta.selectionEnd)||p;insertAtCursor(ta,b+sel+a)} function insertLine(p,ph){insertAtCursor(getEd(),p+(ph||''))} function insertBlock(b,p,a){insertAtCursor(getEd(),b+p+a)} function insertPageWrap(b,a,p){insertAtCursor(getPgEd(),b+p+a);refreshPagePreview()} function insertPageLine(p,ph){insertAtCursor(getPgEd(),p+(ph||''));refreshPagePreview()} function tabKey(e){if(e.key!=='Tab')return;e.preventDefault();insertAtCursor(e.target,'  ')}
    function md(markdown){var html=esc(markdown||'');html=html.replace(/```([\s\S]*?)```/g,function(_,c){return'<pre><code>'+esc(c.trim())+'</code></pre>'});html=html.replace(/^### (.*)$/gm,'<h3>$1</h3>');html=html.replace(/^## (.*)$/gm,'<h2>$1</h2>');html=html.replace(/^# (.*)$/gm,'<h1>$1</h1>');html=html.replace(/^> (.*)$/gm,'<blockquote>$1</blockquote>');html=html.replace(/^- (.*)$/gm,'<li>$1</li>');html=html.replace(/(<li>[\s\S]*?<\/li>)/g,function(m){return'<ul>'+m+'</ul>'});html=html.replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<p><img src="$2" alt="$1" style="max-width:100%;border-radius:8px;"></p>');html=html.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>');html=html.replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');html=html.replace(/\*([^*]+)\*/g,'<em>$1</em>');html=html.replace(/`([^`]+)`/g,'<code>$1</code>');html=html.split(/\n{2,}/).map(function(b){if(/^\s*<(h\d|ul|pre|blockquote|p)/.test(b))return b;return'<p>'+b.replace(/\n/g,'<br>')+'</p>'}).join('');return html||'<p class="muted">Nothing to preview yet.</p>'}
    async function refreshDashboard(){document.getElementById('dash-stats').innerHTML='<div class="loading"><span class="spin"></span> Loading dashboard...</div>';try{if(!postsCache.length)await loadPosts();var keys=Object.keys(PAGE_FILES),pages=[];for(var i=0;i<keys.length;i++){var key=keys[i],f=await ghGetFile(PAGE_FILES[key]),p=parseFM(f.raw);pages.push({key:key,path:PAGE_FILES[key],meta:p.meta,content:p.content})}var pf=await ghGetFile(PORTFOLIO_FILE);portfolioCache=JSON.parse(pf.raw);renderDashboard(postsCache,pages,portfolioCache)}catch(err){showAlert('dashboard-alert','error',esc(err.message))}}
    function stat(label,val){return'<div class="stat"><div class="k">'+esc(label)+'</div><div class="v">'+esc(val)+'</div></div>'}
    function item(label,val){return'<div class="item"><strong>'+esc(label)+'</strong><div class="muted">'+esc(String(val))+'</div></div>'}
    function links(text){var out=[],m,r=/\[[^\]]+\]\(([^)]+)\)/g,h=/href="([^"]+)"/g;while((m=r.exec(text)))out.push(m[1]);while((m=h.exec(text)))out.push(m[1]);return out}
    function health(posts,pages){var issues=[],seen={};posts.forEach(function(p){var t=String(p.meta.title||'').trim();if(!t)issues.push({t:'Missing title',d:p.name});if(!p.meta.description)issues.push({t:'Missing description',d:p.name});if(t){if(seen[t])issues.push({t:'Duplicate title',d:t});seen[t]=1}});var known=Object.keys(PAGE_FILES).map(function(k){return'/'+PAGE_FILES[k].replace(/\.md$/,'/').replace(/index\.html$/,'')}).concat(posts.map(function(p){return postUrl(p.name)}));posts.concat(pages).forEach(function(x){links(x.content||'').forEach(function(l){if(l.startsWith('/')&&!l.startsWith('/assets/')&&known.every(function(r){return l.indexOf(r)!==0}))issues.push({t:'Possible broken internal link',d:l+' in '+(x.name||x.path||x.key)})})});var drafts=posts.filter(function(p){return p.status==='draft'});if(drafts.length)issues.push({t:'Draft posts pending review',d:drafts.length+' draft(s) found.'});return issues.slice(0,12)}
    function renderDashboard(posts,pages,pf){var pub=posts.filter(function(p){return p.status==='published'}).length,dr=posts.filter(function(p){return p.status==='draft'}).length,sch=posts.filter(function(p){return p.status==='scheduled'}).length,words=posts.reduce(function(s,p){return s+String(p.content||'').split(/\s+/).filter(Boolean).length},0);document.getElementById('dash-stats').innerHTML=[stat('Published Posts',pub),stat('Drafts',dr),stat('Scheduled',sch),stat('Pages',pages.length),stat('Portfolio Items',pf.length),stat('Words Published',words)].join('');var hs=health(posts,pages);document.getElementById('dash-health').innerHTML=hs.length?hs.map(function(i){return item(i.t,i.d)}).join(''):item('All clear','No health issues found.');document.getElementById('dash-analytics').innerHTML=[item('Average words per post',posts.length?Math.round(words/posts.length):0),item('Posts with meta descriptions',posts.filter(function(p){return p.meta.description}).length+' of '+posts.length),item('Posts with social images',posts.filter(function(p){return p.meta.social_image}).length+' of '+posts.length)].join('');document.getElementById('dash-summary').innerHTML=[item('Latest post',posts[0]?(posts[0].meta.title||posts[0].name):'No posts yet'),item('Indexable pages',pages.filter(function(p){return p.meta.noindex!==true}).length),item('Tracked policy pages',pages.map(function(p){return p.key}).join(', '))].join('')}
    function exportBackup(type){var payload;if(type==='posts')payload=postsCache.map(function(p){return{path:p.path,meta:p.meta,content:p.content}});else if(type==='portfolio')payload=portfolioCache;else if(type==='pages')payload=Object.keys(PAGE_FILES);else if(type==='settings')payload=siteCache;else payload={posts:postsCache,portfolio:portfolioCache,settings:siteCache,exportedAt:new Date().toISOString()};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='metaxenopy-'+type+'-backup.json';a.click();URL.revokeObjectURL(url)}
    function yamlVal(raw,key){var re=new RegExp('^'+key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+':\\s*"?([^"\\n]*)"?$','m'),m=raw.match(re);return m?m[1]:''}
    function yamlSet(raw,key,val){var re=new RegExp('^'+key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+':\\s*.*$','m'),line=key+': "'+String(val||'').replace(/"/g,'\\"')+'"';return re.test(raw)?raw.replace(re,line):raw.trimEnd()+'\n'+line+'\n'}
    async function prefillSettings(){var tok=load(KEY_TOKEN);if(tok)document.getElementById('st-token').value=tok;try{var cfg=await ghGetFile(CONFIG_FILE);siteCache.configRaw=cfg.raw;siteCache.configSha=cfg.sha;document.getElementById('st-verify').value=yamlVal(cfg.raw,'google_site_verification');document.getElementById('st-pub').value=yamlVal(cfg.raw,'google_adsense_publisher_id');document.getElementById('st-post-slot').value=yamlVal(cfg.raw,'google_adsense_post_slot_id');document.getElementById('st-head-slot').value=yamlVal(cfg.raw,'google_adsense_header_slot_id');document.getElementById('st-foot-slot').value=yamlVal(cfg.raw,'google_adsense_footer_slot_id');var robots=await ghGetFile(ROBOTS_FILE);siteCache.robotsRaw=robots.raw;siteCache.robotsSha=robots.sha;document.getElementById('st-robots').value=robots.raw;var ads=await ghGetFile(ADS_FILE);siteCache.adsRaw=ads.raw;siteCache.adsSha=ads.sha;document.getElementById('st-ads').value=ads.raw;var css=await ghGetFile('assets/css/main.css'),m=css.raw.match(/--color-primary:\s*([^;]+)/);if(m){document.getElementById('st-color').value=m[1].trim();document.getElementById('st-color-text').textContent=m[1].trim()}}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    function saveToken(){var t=document.getElementById('st-token').value.trim();if(!t)return showAlert('settings-alert','error','Token cannot be empty.');store(KEY_TOKEN,t);showAlert('settings-alert','success','GitHub token saved.')}
    async function saveIntegrations(){try{var raw=siteCache.configRaw||(await ghGetFile(CONFIG_FILE)).raw;raw=yamlSet(raw,'google_site_verification',document.getElementById('st-verify').value.trim());raw=yamlSet(raw,'google_adsense_publisher_id',document.getElementById('st-pub').value.trim());raw=yamlSet(raw,'google_adsense_post_slot_id',document.getElementById('st-post-slot').value.trim());raw=yamlSet(raw,'google_adsense_header_slot_id',document.getElementById('st-head-slot').value.trim());raw=yamlSet(raw,'google_adsense_footer_slot_id',document.getElementById('st-foot-slot').value.trim());await ghPutFile(CONFIG_FILE,raw,siteCache.configSha,'Update site integrations');var r=await ghGetFile(CONFIG_FILE);siteCache.configRaw=r.raw;siteCache.configSha=r.sha;showAlert('settings-alert','success','Search Console and AdSense settings saved.')}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    async function saveTextFiles(){try{await ghPutFile(ROBOTS_FILE,document.getElementById('st-robots').value,siteCache.robotsSha,'Update robots.txt');var r1=await ghGetFile(ROBOTS_FILE);siteCache.robotsSha=r1.sha;await ghPutFile(ADS_FILE,document.getElementById('st-ads').value,siteCache.adsSha,'Update ads.txt');var r2=await ghGetFile(ADS_FILE);siteCache.adsSha=r2.sha;showAlert('settings-alert','success','robots.txt and ads.txt saved.')}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    async function changePassword(){var oldp=document.getElementById('st-old').value,newp=document.getElementById('st-new').value,conf=document.getElementById('st-confirm').value;if(await sha256(oldp)!==load(KEY_HASH))return showAlert('settings-alert','error','Current password is incorrect.');if(!newp)return showAlert('settings-alert','error','New password is required.');if(newp!==conf)return showAlert('settings-alert','error','Passwords do not match.');store(KEY_HASH,await sha256(newp));createSession();showAlert('settings-alert','success','Password changed successfully.')}
    function resetAdmin(){if(!confirm('Reset locally stored admin credentials in this browser?'))return;[KEY_HASH,KEY_TOKEN,KEY_SESSION,KEY_SESSION_EXP,KEY_POST_AUTOSAVE].forEach(remove);logout()}
    async function updateTheme(){try{var color=document.getElementById('st-color').value,css=await ghGetFile('assets/css/main.css'),updated=css.raw.replace(/(--color-primary:\s*)[^;]+/,'$1'+color);await ghPutFile('assets/css/main.css',updated,css.sha,'Update theme colors');document.getElementById('st-color-text').textContent=color;showAlert('settings-alert','success','Theme color updated.')}catch(err){showAlert('settings-alert','error',esc(err.message))}}
    async function uploadLogo(){var f=document.getElementById('st-logo').files[0];if(!f)return showAlert('settings-alert','error','Select a logo file first.');await putBinary(f,'assets/images/logo.png','Update logo');showAlert('settings-alert','success','Logo uploaded.')}
    async function uploadFavicon(){var f=document.getElementById('st-favicon').files[0];if(!f)return showAlert('settings-alert','error','Select a favicon file first.');await putBinary(f,'assets/images/favicon.ico','Update favicon');showAlert('settings-alert','success','Favicon uploaded.')}
    function copyText(t){navigator.clipboard.writeText(t).then(function(){showAlert('media-alert','success','Copied to clipboard.')}).catch(function(){})}
    document.addEventListener('DOMContentLoaded',function(){var color=document.getElementById('st-color');if(color){color.addEventListener('input',function(){document.getElementById('st-color-text').textContent=this.value})}if(isAuthenticated())enterAdmin();else initAuth()})
